"""fix_gift_inventory_price_types

Revision ID: 096ff697eef8
Revises: aac5200a3abf
Create Date: 2026-06-10 09:19:27.033135
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096ff697eef8'
down_revision: Union[str, None] = 'aac5200a3abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gift_inventories', 'unit_price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=4),
               existing_comment='单价',
               existing_nullable=True,
               schema='administration')
    op.alter_column('gift_inventories', 'total_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=4),
               existing_comment='金额',
               existing_nullable=True,
               schema='administration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gift_inventories', 'total_amount',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.INTEGER(),
               existing_comment='金额',
               existing_nullable=True,
               schema='administration')
    op.alter_column('gift_inventories', 'unit_price',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.INTEGER(),
               existing_comment='单价',
               existing_nullable=True,
               schema='administration')
    # ### end Alembic commands ###
