"""remove_product_status_and_convert_capacity_range_to_text

Revision ID: 1708e4a95e16
Revises: ef61a860eb16
Create Date: 2026-06-08 09:44:25.864775
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1708e4a95e16'
down_revision: Union[str, None] = 'ef61a860eb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 添加临时文本列
    op.add_column('products', sa.Column('capacity_range_tmp', sa.String(length=256), nullable=True, comment='生产批量（逗号分隔）'), schema='product')
    # 2. 将 JSON 数据转换为逗号分隔文本（数组转逗号分隔，标量直接转文本）
    op.execute("""
        UPDATE product.products
        SET capacity_range_tmp = CASE
            WHEN json_typeof(capacity_range) = 'array' THEN (
                SELECT string_agg(elem::text, ', ')
                FROM json_array_elements_text(capacity_range) AS elem
            )
            ELSE capacity_range::text
        END
        WHERE capacity_range IS NOT NULL
    """)
    # 3. 删除原 JSON 列
    op.drop_column('products', 'capacity_range', schema='product')
    # 4. 重命名临时列为正式列
    op.alter_column('products', 'capacity_range_tmp', new_column_name='capacity_range', schema='product')

    op.drop_index(op.f('ix_products_status'), table_name='products', schema='product')
    op.drop_column('products', 'status', schema='product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'临床阶段'::character varying"), autoincrement=False, nullable=False, comment='产品状态: 临床阶段, 商业化生产阶段, 产品暂停'), schema='product')
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False, schema='product')
    op.alter_column('products', 'capacity_range',
               existing_type=sa.String(length=256),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment='生产批量（多选）',
               existing_comment='生产批量（逗号分隔）',
               existing_nullable=True,
               schema='product')
    # ### end Alembic commands ###
