"""add regulations table

Revision ID: 20250609_0001
Revises: 65acf67e248f
Create Date: 2026-06-09 10:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250609_0001'
down_revision: Union[str, None] = '65acf67e248f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulations',
    sa.Column('title', sa.String(length=256), nullable=False, comment='制度名称'),
    sa.Column('content', sa.Text(), nullable=False, comment='制度内容'),
    sa.Column('file_name', sa.String(length=256), nullable=True, comment='原始文件名'),
    sa.Column('file_type', sa.String(length=128), nullable=True, comment='文件类型'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='administration'
    )
    op.create_index('ix_regulations_title', 'regulations', ['title'], unique=False, schema='administration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_regulations_title', table_name='regulations', schema='administration')
    op.drop_table('regulations', schema='administration')
    # ### end Alembic commands ###
