"""add_candidates_table

Revision ID: 25374aeacec3
Revises: 2eba70488232
Create Date: 2026-06-09 14:51:10.849013
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25374aeacec3'
down_revision: Union[str, None] = '2eba70488232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('name', sa.String(length=64), nullable=False, comment='候选人姓名'),
    sa.Column('position', sa.String(length=64), nullable=False, comment='应聘职位名称'),
    sa.Column('gender', sa.String(length=8), nullable=True, comment='性别'),
    sa.Column('school', sa.String(length=128), nullable=True, comment='学校名称'),
    sa.Column('education', sa.String(length=16), nullable=True, comment='学历'),
    sa.Column('major', sa.String(length=64), nullable=True, comment='专业'),
    sa.Column('match_report', sa.Text(), nullable=True, comment='候选人匹配度报告'),
    sa.Column('recommendation_level', sa.String(length=16), nullable=True, comment='推荐等级'),
    sa.Column('resume_attachments', sa.JSON(), nullable=True, comment='简历附件元数据'),
    sa.Column('feishu_record_id', sa.String(length=32), nullable=True, comment='飞书多维表格 record_id'),
    sa.Column('feishu_synced_at', sa.Date(), nullable=True, comment='上次飞书同步时间'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_candidates_feishu_record_id', 'candidates', ['feishu_record_id'], unique=False, schema='hr')
    op.create_index('ix_candidates_name', 'candidates', ['name'], unique=False, schema='hr')
    op.create_index('ix_candidates_position', 'candidates', ['position'], unique=False, schema='hr')
    op.create_index('ix_candidates_recommendation_level', 'candidates', ['recommendation_level'], unique=False, schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidates_recommendation_level', table_name='candidates', schema='hr')
    op.drop_index('ix_candidates_position', table_name='candidates', schema='hr')
    op.drop_index('ix_candidates_name', table_name='candidates', schema='hr')
    op.drop_index('ix_candidates_feishu_record_id', table_name='candidates', schema='hr')
    op.drop_table('candidates', schema='hr')
    # ### end Alembic commands ###
