"""make_offboarding_date_nullable_remarks_text

Revision ID: 2eba70488232
Revises: 96d829b2ba78
Create Date: 2026-06-07 22:53:56.925095
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2eba70488232'
down_revision: Union[str, None] = '96d829b2ba78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departure_records', 'offboarding_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_comment='离职日期',
               schema='hr')
    op.alter_column('departure_records', 'remarks',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               comment='备注',
               existing_comment='备注（多选）',
               existing_nullable=True,
               schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departure_records', 'remarks',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment='备注（多选）',
               existing_comment='备注',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'offboarding_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_comment='离职日期',
               schema='hr')
    # ### end Alembic commands ###
