"""add product module schema and table

Revision ID: 5b2c0228befb
Revises: ec4654a030c0
Create Date: 2026-06-08 08:44:42.006627
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2c0228befb'
down_revision: Union[str, None] = 'ec4654a030c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS product")
    op.create_table('products',
    sa.Column('name', sa.String(length=128), nullable=False, comment='产品名称'),
    sa.Column('spec', sa.String(length=128), nullable=True, comment='规格包装'),
    sa.Column('item_number', sa.String(length=64), nullable=True, comment='料件编号'),
    sa.Column('major_category', sa.String(length=32), nullable=True, comment='产品大类: SM, FSM'),
    sa.Column('product_type', sa.String(length=32), nullable=True, comment='产品类别: SM2, SM8, API, 产品, 包装'),
    sa.Column('market', sa.String(length=32), nullable=True, comment='市场: 中国市场, 海外市场, 海外/中国'),
    sa.Column('capacity_range', sa.JSON(), nullable=True, comment='产能范围（多选）'),
    sa.Column('unit', sa.String(length=16), nullable=True, comment='单位: 支, g'),
    sa.Column('indication', sa.String(length=64), nullable=True, comment='适应症'),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=2), nullable=True, comment='成本单价/元'),
    sa.Column('tax_price', sa.Numeric(precision=18, scale=2), nullable=True, comment='含税单价/元'),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='增值税税率'),
    sa.Column('untax_price', sa.Numeric(precision=18, scale=2), nullable=True, comment='不含税单价/元'),
    sa.Column('workshop', sa.String(length=64), nullable=True, comment='生产车间'),
    sa.Column('product_images', sa.JSON(), nullable=True, comment='产品图片（飞书附件JSON）'),
    sa.Column('inspection_reports', sa.JSON(), nullable=True, comment='产品检验报告（飞书附件JSON）'),
    sa.Column('product_permission', sa.String(length=64), nullable=True, comment='产品权限'),
    sa.Column('acquisition_method', sa.String(length=64), nullable=True, comment='获取方式'),
    sa.Column('bom_link_ids', sa.JSON(), nullable=True, comment='BOM清单关联record_id列表'),
    sa.Column('process_route_link_ids', sa.JSON(), nullable=True, comment='产品工艺路线关联record_id列表'),
    sa.Column('status', sa.String(length=32), server_default='临床阶段', nullable=False, comment='产品状态: 临床阶段, 商业化生产阶段, 产品暂停'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('feishu_record_id', sa.String(length=32), nullable=True, comment='飞书多维表格 record_id'),
    sa.Column('feishu_synced_at', sa.Date(), nullable=True, comment='上次飞书同步时间'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='product'
    )
    op.create_index('ix_products_feishu_record_id', 'products', ['feishu_record_id'], unique=False, schema='product')
    op.create_index('ix_products_major_category', 'products', ['major_category'], unique=False, schema='product')
    op.create_index('ix_products_name', 'products', ['name'], unique=False, schema='product')
    op.create_index('ix_products_product_type', 'products', ['product_type'], unique=False, schema='product')
    op.create_index('ix_products_status', 'products', ['status'], unique=False, schema='product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_status', table_name='products', schema='product')
    op.drop_index('ix_products_product_type', table_name='products', schema='product')
    op.drop_index('ix_products_name', table_name='products', schema='product')
    op.drop_index('ix_products_major_category', table_name='products', schema='product')
    op.drop_index('ix_products_feishu_record_id', table_name='products', schema='product')
    op.drop_table('products', schema='product')
    # ### end Alembic commands ###
