"""update product table to match feishu fields

Revision ID: 92e999b5f8cc
Revises: 5b2c0228befb
Create Date: 2026-06-08 09:15:40.270303
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92e999b5f8cc'
down_revision: Union[str, None] = '5b2c0228befb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('formulation_code', sa.String(length=32), nullable=True, comment='制剂代码: AA, AB, AC...'), schema='product')
    op.alter_column('products', 'spec',
               existing_type=sa.VARCHAR(length=128),
               comment='生产规格',
               existing_comment='规格包装',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'major_category',
               existing_type=sa.VARCHAR(length=32),
               comment='产品代码: SM, FSM',
               existing_comment='产品大类: SM, FSM',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'product_type',
               existing_type=sa.VARCHAR(length=32),
               comment='产品剂型: API, 制品, 包装',
               existing_comment='产品类别: SM2, SM8, API, 产品, 包装',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'market',
               existing_type=sa.VARCHAR(length=32),
               comment='市场',
               existing_comment='市场: 中国市场, 海外市场, 海外/中国',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'capacity_range',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='生产批量（多选）',
               existing_comment='产能范围（多选）',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=16),
               comment='单位: 支, g, 批',
               existing_comment='单位: 支, g',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'untax_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='销售单价不含税/元',
               existing_comment='不含税单价/元',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'bom_link_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='BOM关联record_id列表',
               existing_comment='BOM清单关联record_id列表',
               existing_nullable=True,
               schema='product')
    op.drop_column('products', 'cost_price', schema='product')
    op.drop_column('products', 'remarks', schema='product')
    op.drop_column('products', 'vat_rate', schema='product')
    op.drop_column('products', 'acquisition_method', schema='product')
    op.drop_column('products', 'tax_price', schema='product')
    op.drop_column('products', 'product_permission', schema='product')
    op.drop_column('products', 'item_number', schema='product')
    op.drop_column('products', 'inspection_reports', schema='product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('inspection_reports', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='产品检验报告（飞书附件JSON）'), schema='product')
    op.add_column('products', sa.Column('item_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='料件编号'), schema='product')
    op.add_column('products', sa.Column('product_permission', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='产品权限'), schema='product')
    op.add_column('products', sa.Column('tax_price', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True, comment='含税单价/元'), schema='product')
    op.add_column('products', sa.Column('acquisition_method', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='获取方式'), schema='product')
    op.add_column('products', sa.Column('vat_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True, comment='增值税税率'), schema='product')
    op.add_column('products', sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'), schema='product')
    op.add_column('products', sa.Column('cost_price', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True, comment='成本单价/元'), schema='product')
    op.alter_column('products', 'bom_link_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='BOM清单关联record_id列表',
               existing_comment='BOM关联record_id列表',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'untax_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='不含税单价/元',
               existing_comment='销售单价不含税/元',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=16),
               comment='单位: 支, g',
               existing_comment='单位: 支, g, 批',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'capacity_range',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='产能范围（多选）',
               existing_comment='生产批量（多选）',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'market',
               existing_type=sa.VARCHAR(length=32),
               comment='市场: 中国市场, 海外市场, 海外/中国',
               existing_comment='市场',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'product_type',
               existing_type=sa.VARCHAR(length=32),
               comment='产品类别: SM2, SM8, API, 产品, 包装',
               existing_comment='产品剂型: API, 制品, 包装',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'major_category',
               existing_type=sa.VARCHAR(length=32),
               comment='产品大类: SM, FSM',
               existing_comment='产品代码: SM, FSM',
               existing_nullable=True,
               schema='product')
    op.alter_column('products', 'spec',
               existing_type=sa.VARCHAR(length=128),
               comment='规格包装',
               existing_comment='生产规格',
               existing_nullable=True,
               schema='product')
    op.drop_column('products', 'formulation_code', schema='product')
    # ### end Alembic commands ###
