"""widen_household_marital_columns

Revision ID: 96d829b2ba78
Revises: 18477a05243b
Create Date: 2026-06-07 22:52:29.538352
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d829b2ba78'
down_revision: Union[str, None] = '18477a05243b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departure_records', 'household_type',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=128),
               existing_comment='户籍类型',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'marital_status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_comment='婚姻状况',
               existing_nullable=True,
               schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departure_records', 'marital_status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_comment='婚姻状况',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'household_type',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=16),
               existing_comment='户籍类型',
               existing_nullable=True,
               schema='hr')
    # ### end Alembic commands ###
