"""add tracking_status to annual plan items

Revision ID: 9b0db8aefc3f
Revises: 159bd28c9a19
Create Date: 2026-06-12 09:13:42.308131
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0db8aefc3f'
down_revision: Union[str, None] = '159bd28c9a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annual_training_plan_items', sa.Column('tracking_status', sa.String(length=16), nullable=True, comment='培训跟踪: 完成, 未完成'), schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annual_training_plan_items', 'tracking_status', schema='hr')
    # ### end Alembic commands ###
