"""add_gift_inventories_table

Revision ID: aac5200a3abf
Revises: 20250609_0003
Create Date: 2026-06-10 09:15:42.653654
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac5200a3abf'
down_revision: Union[str, None] = '20250609_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_inventories',
    sa.Column('name', sa.String(length=128), nullable=False, comment='物品名称'),
    sa.Column('specification', sa.String(length=64), nullable=True, comment='规格'),
    sa.Column('unit', sa.String(length=16), nullable=True, comment='计量单位'),
    sa.Column('opening_stock', sa.Integer(), server_default='0', nullable=False, comment='月初库存'),
    sa.Column('incoming_qty', sa.Integer(), nullable=True, comment='本期入库/领用数量'),
    sa.Column('closing_stock', sa.Integer(), server_default='0', nullable=False, comment='月底库存'),
    sa.Column('unit_price', sa.Integer(), nullable=True, comment='单价'),
    sa.Column('total_amount', sa.Integer(), nullable=True, comment='金额'),
    sa.Column('status', sa.String(length=16), server_default='可用', nullable=False, comment='状态: 可用, 库存不足, 停用'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='administration'
    )
    op.create_index('ix_gift_inventories_name', 'gift_inventories', ['name'], unique=False, schema='administration')
    op.create_index('ix_gift_inventories_status', 'gift_inventories', ['status'], unique=False, schema='administration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gift_inventories_status', table_name='gift_inventories', schema='administration')
    op.drop_index('ix_gift_inventories_name', table_name='gift_inventories', schema='administration')
    op.drop_table('gift_inventories', schema='administration')
    # ### end Alembic commands ###
