"""simplify product table to 8 core fields

Revision ID: ef61a860eb16
Revises: 92e999b5f8cc
Create Date: 2026-06-08 09:29:41.652116
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef61a860eb16'
down_revision: Union[str, None] = '92e999b5f8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'process_route_link_ids', schema='product')
    op.drop_column('products', 'product_images', schema='product')
    op.drop_column('products', 'bom_link_ids', schema='product')
    op.drop_column('products', 'market', schema='product')
    op.drop_column('products', 'workshop', schema='product')
    op.drop_column('products', 'untax_price', schema='product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('untax_price', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True, comment='销售单价不含税/元'), schema='product')
    op.add_column('products', sa.Column('workshop', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='生产车间'), schema='product')
    op.add_column('products', sa.Column('market', sa.VARCHAR(length=32), autoincrement=False, nullable=True, comment='市场'), schema='product')
    op.add_column('products', sa.Column('bom_link_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='BOM关联record_id列表'), schema='product')
    op.add_column('products', sa.Column('product_images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='产品图片（飞书附件JSON）'), schema='product')
    op.add_column('products', sa.Column('process_route_link_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='产品工艺路线关联record_id列表'), schema='product')
    # ### end Alembic commands ###
