"""add feishu_sync_status to candidates

Revision ID: f3a9e2b1c8d4
Revises: cfdc2edb97f7
Create Date: 2026-06-11 10:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a9e2b1c8d4'
down_revision: Union[str, None] = 'cfdc2edb97f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('feishu_sync_status', sa.String(length=16), nullable=True, comment='飞书同步状态: synced/failed'), schema='hr')
    op.add_column('candidates', sa.Column('feishu_sync_error', sa.Text(), nullable=True, comment='飞书同步失败原因'), schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'feishu_sync_error', schema='hr')
    op.drop_column('candidates', 'feishu_sync_status', schema='hr')
    # ### end Alembic commands ###
