"""audit_restore_fk_constraints

Revision ID: 030b01754e94
Revises: d2dfea3363e9
Create Date: 2026-06-30 11:38:00
"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '030b01754e94'
down_revision: str | None = 'd2dfea3363e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'logs', 'users', ['user_id'], ['id'], source_schema='audit', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', schema='audit', type_='foreignkey')
    # ### end Alembic commands ###
