"""add_training_ledger_pages

Revision ID: 0eedc1cd3579
Revises: 9061fd906b65
Create Date: 2026-06-11 16:03:00.070729
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eedc1cd3579'
down_revision: Union[str, None] = '9061fd906b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_ledger_pages',
    sa.Column('employee_number', sa.String(length=32), nullable=False, comment='工号'),
    sa.Column('employee_name', sa.String(length=64), nullable=False, comment='员工姓名'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_number'),
    schema='hr'
    )
    op.create_index('ix_training_ledger_pages_employee_number', 'training_ledger_pages', ['employee_number'], unique=True, schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_ledger_pages_employee_number', table_name='training_ledger_pages', schema='hr')
    op.drop_table('training_ledger_pages', schema='hr')
    # ### end Alembic commands ###
