"""add_departure_records_table

Revision ID: 0fa21e960485
Revises: 8b5af1b48c8a
Create Date: 2026-06-07 21:35:10.428857
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa21e960485'
down_revision: Union[str, None] = '8b5af1b48c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departure_records',
    sa.Column('name', sa.String(length=64), nullable=False, comment='姓名'),
    sa.Column('department', sa.String(length=64), nullable=False, comment='部门'),
    sa.Column('team', sa.String(length=64), nullable=True, comment='班组'),
    sa.Column('position', sa.String(length=64), nullable=False, comment='职位'),
    sa.Column('job_category', sa.String(length=32), nullable=True, comment='职类'),
    sa.Column('gender', sa.String(length=8), nullable=True, comment='性别'),
    sa.Column('status_category', sa.String(length=32), nullable=True, comment='统计类别'),
    sa.Column('livo_entry_date', sa.Date(), nullable=True, comment='入丽珠时间'),
    sa.Column('factory_entry_date', sa.Date(), nullable=True, comment='进厂时间'),
    sa.Column('work_start_date', sa.Date(), nullable=True, comment='参加工作时间'),
    sa.Column('offboarding_date', sa.Date(), nullable=False, comment='离职日期'),
    sa.Column('company_tenure_at_leave', sa.String(length=32), nullable=True, comment='离职时司龄'),
    sa.Column('education', sa.String(length=16), nullable=True, comment='学历'),
    sa.Column('school', sa.String(length=128), nullable=True, comment='毕业学校'),
    sa.Column('major', sa.String(length=64), nullable=True, comment='专业'),
    sa.Column('classification', sa.String(length=16), nullable=True, comment='分类：全日制/非全日制'),
    sa.Column('id_card', sa.String(length=18), nullable=True, comment='身份证号'),
    sa.Column('native_place', sa.String(length=64), nullable=True, comment='籍贯'),
    sa.Column('household_type', sa.String(length=16), nullable=True, comment='户籍类型'),
    sa.Column('marital_status', sa.String(length=16), nullable=True, comment='婚姻状况'),
    sa.Column('political_status', sa.String(length=32), nullable=True, comment='政治面貌'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='手机'),
    sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True, comment='紧急联系人电话'),
    sa.Column('emergency_contact_relation', sa.String(length=32), nullable=True, comment='紧急联系人|关系'),
    sa.Column('bank_account', sa.String(length=32), nullable=True, comment='银行卡号'),
    sa.Column('contract_type', sa.String(length=32), nullable=True, comment='合同期限'),
    sa.Column('transfer_history', sa.Text(), nullable=True, comment='异动（含曾经工作部门、岗位)'),
    sa.Column('offboarding_type', sa.String(length=16), server_default='辞职', nullable=False, comment='离职类型: 辞职, 辞退, 合同到期, 退休, 其他'),
    sa.Column('offboarding_reason', sa.JSON(), nullable=True, comment='离职原因（多选）'),
    sa.Column('offboarding_reason_2', sa.JSON(), nullable=True, comment='离职原因2（多选）'),
    sa.Column('offboarding_remarks', sa.JSON(), nullable=True, comment='离职备注（多选）'),
    sa.Column('remarks', sa.JSON(), nullable=True, comment='备注（多选）'),
    sa.Column('feishu_record_id', sa.String(length=32), nullable=True, comment='飞书多维表格 record_id'),
    sa.Column('feishu_synced_at', sa.Date(), nullable=True, comment='上次飞书同步时间'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_departure_department', 'departure_records', ['department'], unique=False, schema='hr')
    op.create_index('ix_departure_feishu_record_id', 'departure_records', ['feishu_record_id'], unique=False, schema='hr')
    op.create_index('ix_departure_offboarding_date', 'departure_records', ['offboarding_date'], unique=False, schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_departure_offboarding_date', table_name='departure_records', schema='hr')
    op.drop_index('ix_departure_feishu_record_id', table_name='departure_records', schema='hr')
    op.drop_index('ix_departure_department', table_name='departure_records', schema='hr')
    op.drop_table('departure_records', schema='hr')
    # ### end Alembic commands ###
