"""add annual_training_plan tables

Revision ID: 159bd28c9a19
Revises: 0eedc1cd3579
Create Date: 2026-06-12 08:40:31.983280
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159bd28c9a19'
down_revision: Union[str, None] = '0eedc1cd3579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_training_plans',
    sa.Column('year', sa.Integer(), nullable=False, comment='年度'),
    sa.Column('department', sa.String(length=64), nullable=False, comment='部门'),
    sa.Column('status', sa.String(length=16), server_default='草稿', nullable=False, comment='状态: 草稿, 已确认'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_annual_training_plans_department', 'annual_training_plans', ['department'], unique=False, schema='hr')
    op.create_index('ix_annual_training_plans_year', 'annual_training_plans', ['year'], unique=False, schema='hr')
    op.create_table('annual_training_plan_items',
    sa.Column('plan_id', sa.Uuid(), nullable=False, comment='年度计划ID'),
    sa.Column('month', sa.String(length=16), nullable=True, comment='月份'),
    sa.Column('trainee_count', sa.Integer(), nullable=True, comment='培训人数'),
    sa.Column('duration_hours', sa.Float(), nullable=True, comment='课时'),
    sa.Column('content_and_textbook', sa.String(length=512), nullable=True, comment='培训内容及使用教材'),
    sa.Column('target_audience', sa.String(length=256), nullable=True, comment='培训对象'),
    sa.Column('position_and_count', sa.String(length=256), nullable=True, comment='参加岗位/参加人数'),
    sa.Column('training_method', sa.String(length=64), nullable=True, comment='培训方式'),
    sa.Column('training_hours', sa.Float(), nullable=True, comment='培训学时'),
    sa.Column('confirmer', sa.String(length=64), nullable=True, comment='确认者'),
    sa.Column('confirm_date', sa.Date(), nullable=True, comment='确认日期'),
    sa.Column('remarks', sa.String(length=512), nullable=True, comment='备注'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['hr.annual_training_plans.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_annual_training_plan_items_plan_id', 'annual_training_plan_items', ['plan_id'], unique=False, schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_annual_training_plan_items_plan_id', table_name='annual_training_plan_items', schema='hr')
    op.drop_table('annual_training_plan_items', schema='hr')
    op.drop_index('ix_annual_training_plans_year', table_name='annual_training_plans', schema='hr')
    op.drop_index('ix_annual_training_plans_department', table_name='annual_training_plans', schema='hr')
    op.drop_table('annual_training_plans', schema='hr')
    # ### end Alembic commands ###
