"""widen_departure_string_columns

Revision ID: 18477a05243b
Revises: 0fa21e960485
Create Date: 2026-06-07 22:51:16.488929
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18477a05243b'
down_revision: Union[str, None] = '0fa21e960485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departure_records', 'job_category',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='职类',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'status_category',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='统计类别',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'company_tenure_at_leave',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='离职时司龄',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'political_status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='政治面貌',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'emergency_contact_relation',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='紧急联系人|关系',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'bank_account',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_comment='银行卡号',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'contract_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='合同期限',
               existing_nullable=True,
               schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departure_records', 'contract_type',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='合同期限',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'bank_account',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_comment='银行卡号',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'emergency_contact_relation',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='紧急联系人|关系',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'political_status',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='政治面貌',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'company_tenure_at_leave',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='离职时司龄',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'status_category',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='统计类别',
               existing_nullable=True,
               schema='hr')
    op.alter_column('departure_records', 'job_category',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='职类',
               existing_nullable=True,
               schema='hr')
    # ### end Alembic commands ###
