"""initial sqlite migration

Revision ID: 19cbfbe7445a
Revises: 
Create Date: 2026-06-06 15:51:50.472702
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19cbfbe7445a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('employee_no', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('feishu_user_id', sa.String(length=128), nullable=True),
    sa.Column('feishu_open_id', sa.String(length=128), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_no', name='uq_identity_users_employee_no'),
    sa.UniqueConstraint('feishu_user_id', name='uq_identity_users_feishu_user_id')
    )
    op.create_table('departments',
    sa.Column('name', sa.String(length=64), nullable=False, comment='部门名称'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='部门编码'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='部门描述'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_departments_code', 'departments', ['code'], unique=False)
    op.create_table('employees',
    sa.Column('employee_number', sa.String(length=32), nullable=False, comment='工号'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='姓名'),
    sa.Column('domain_account', sa.String(length=64), nullable=True, comment='域账号'),
    sa.Column('department', sa.String(length=64), nullable=False, comment='部门'),
    sa.Column('team', sa.String(length=64), nullable=True, comment='班组'),
    sa.Column('position', sa.String(length=64), nullable=False, comment='职位'),
    sa.Column('job_category', sa.String(length=32), nullable=True, comment='职类'),
    sa.Column('level', sa.String(length=32), nullable=True, comment='级别'),
    sa.Column('qualifications', sa.JSON(), nullable=True, comment='职称／职业资格（多选）'),
    sa.Column('qualification_type', sa.String(length=32), nullable=True, comment='职称类型'),
    sa.Column('gender', sa.String(length=8), nullable=True, comment='性别'),
    sa.Column('native_place', sa.String(length=64), nullable=True, comment='籍贯'),
    sa.Column('political_status', sa.String(length=32), nullable=True, comment='政治面貌'),
    sa.Column('marital_status', sa.String(length=16), nullable=True, comment='婚姻状况'),
    sa.Column('household_type', sa.String(length=16), nullable=True, comment='户籍类型'),
    sa.Column('status_category', sa.String(length=32), nullable=True, comment='统计类别'),
    sa.Column('birth_year', sa.Integer(), nullable=True, comment='出生年份'),
    sa.Column('birth_month', sa.Integer(), nullable=True, comment='出生月份'),
    sa.Column('birth_day', sa.Integer(), nullable=True, comment='出生日期'),
    sa.Column('age', sa.Integer(), nullable=True, comment='年龄（飞书公式）'),
    sa.Column('work_start_date', sa.Date(), nullable=True, comment='参加工作时间'),
    sa.Column('factory_entry_date', sa.Date(), nullable=True, comment='进厂时间'),
    sa.Column('livo_entry_date', sa.Date(), nullable=True, comment='入丽珠时间'),
    sa.Column('hire_date', sa.Date(), nullable=False, comment='入职日期'),
    sa.Column('graduation_date', sa.Date(), nullable=True, comment='毕业时间'),
    sa.Column('work_years', sa.Integer(), nullable=True, comment='工作年限（飞书公式）'),
    sa.Column('factory_tenure', sa.String(length=32), nullable=True, comment='厂龄（飞书公式）'),
    sa.Column('company_tenure', sa.String(length=32), nullable=True, comment='司龄（飞书公式）'),
    sa.Column('education', sa.String(length=16), nullable=True, comment='学历'),
    sa.Column('classification', sa.String(length=16), nullable=True, comment='分类：全日制/非全日制'),
    sa.Column('school', sa.String(length=128), nullable=True, comment='毕业学校'),
    sa.Column('major', sa.String(length=64), nullable=True, comment='专业'),
    sa.Column('id_card', sa.String(length=18), nullable=True, comment='身份证号'),
    sa.Column('id_card_expiry', sa.String(length=32), nullable=True, comment='身份证到期日'),
    sa.Column('id_card_address', sa.Text(), nullable=True, comment='身份证地址|家庭地址'),
    sa.Column('current_address', sa.Text(), nullable=True, comment='现住址'),
    sa.Column('contract_type', sa.String(length=32), nullable=True, comment='合同期限'),
    sa.Column('contract_start_date', sa.Date(), nullable=True, comment='合同开始日期（第一次）'),
    sa.Column('contract_end_date', sa.Date(), nullable=True, comment='合同结束日期（第一次）'),
    sa.Column('contract_start_2', sa.Date(), nullable=True, comment='第二次合同起点'),
    sa.Column('contract_end_2', sa.Date(), nullable=True, comment='第二次合同终止'),
    sa.Column('contract_start_3', sa.Date(), nullable=True, comment='第三次合同起点'),
    sa.Column('contract_end_3', sa.Date(), nullable=True, comment='第三次合同终止'),
    sa.Column('contract_start_4', sa.Date(), nullable=True, comment='第四次合同起点'),
    sa.Column('contract_end_4', sa.Date(), nullable=True, comment='第四次合同终止'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='手机'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('emergency_contact_name', sa.String(length=64), nullable=True, comment='紧急联系人姓名'),
    sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True, comment='紧急联系人电话'),
    sa.Column('emergency_contact_relation', sa.String(length=32), nullable=True, comment='紧急联系人关系'),
    sa.Column('bank_account', sa.String(length=32), nullable=True, comment='银行卡号'),
    sa.Column('training_id', sa.String(length=32), nullable=True, comment='培训档案编号'),
    sa.Column('transfer_history', sa.Text(), nullable=True, comment='异动（含曾经工作部门、岗位)'),
    sa.Column('remarks', sa.JSON(), nullable=True, comment='备注（多选）'),
    sa.Column('status', sa.String(length=16), server_default='待审批', nullable=False, comment='状态: 在职, 离职, 试用期, 待审批'),
    sa.Column('feishu_record_id', sa.String(length=32), nullable=True, comment='飞书多维表格 record_id'),
    sa.Column('feishu_synced_at', sa.Date(), nullable=True, comment='上次飞书同步时间'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_number')
    )
    op.create_index('ix_employees_department', 'employees', ['department'], unique=False)
    op.create_index('ix_employees_employee_number', 'employees', ['employee_number'], unique=False)
    op.create_index('ix_employees_feishu_record_id', 'employees', ['feishu_record_id'], unique=False)
    op.create_index('ix_employees_status', 'employees', ['status'], unique=False)
    op.create_table('equipment_categories',
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='分类代码'),
    sa.Column('parent_id', sa.Uuid(), nullable=True, comment='父分类ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='分类描述'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['equipment_categories.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'is_deleted', name='uq_equipment_categories_code')
    )
    op.create_table('failure_actions',
    sa.Column('code', sa.String(length=50), nullable=False, comment='维修措施代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='维修措施名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='维修措施描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'is_deleted', name='uq_failure_actions_code')
    )
    op.create_table('failure_causes',
    sa.Column('code', sa.String(length=50), nullable=False, comment='故障原因代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='故障原因名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='故障原因描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'is_deleted', name='uq_failure_causes_code')
    )
    op.create_table('failure_symptoms',
    sa.Column('code', sa.String(length=50), nullable=False, comment='故障现象代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='故障现象名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='故障现象描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'is_deleted', name='uq_failure_symptoms_code')
    )
    op.create_table('locations',
    sa.Column('name', sa.String(length=100), nullable=False, comment='位置名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='位置代码'),
    sa.Column('parent_id', sa.Uuid(), nullable=True, comment='父位置ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='位置描述'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'is_deleted', name='uq_locations_code')
    )
    op.create_table('logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_created_at', 'logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_request_id', 'logs', ['request_id'], unique=False)
    op.create_index('idx_audit_logs_resource', 'logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'logs', ['user_id'], unique=False)
    op.create_table('equipments',
    sa.Column('equipment_no', sa.String(length=50), nullable=False, comment='设备编号'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='设备名称'),
    sa.Column('category_id', sa.Uuid(), nullable=False, comment='设备分类'),
    sa.Column('location_id', sa.Uuid(), nullable=False, comment='设备位置'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='设备状态：在用/备用/维修中/停用/报废'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='设备型号'),
    sa.Column('specification', sa.String(length=200), nullable=True, comment='设备规格'),
    sa.Column('manufacturer', sa.String(length=200), nullable=True, comment='制造商'),
    sa.Column('supplier', sa.String(length=200), nullable=True, comment='供应商'),
    sa.Column('production_date', sa.Date(), nullable=True, comment='出厂日期'),
    sa.Column('commissioning_date', sa.Date(), nullable=True, comment='投用日期'),
    sa.Column('description', sa.Text(), nullable=True, comment='设备描述'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("status IN ('在用', '备用', '维修中', '停用', '报废')", name='ck_equipments_status'),
    sa.ForeignKeyConstraint(['category_id'], ['equipment_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_no', 'is_deleted', name='uq_equipments_equipment_no')
    )
    op.create_table('offboarding_records',
    sa.Column('employee_id', sa.Uuid(), nullable=False, comment='员工ID'),
    sa.Column('offboarding_date', sa.Date(), nullable=False, comment='离职日期'),
    sa.Column('offboarding_type', sa.String(length=16), server_default='辞职', nullable=False, comment='离职类型: 辞职, 辞退, 合同到期, 退休, 其他'),
    sa.Column('reason', sa.String(length=512), nullable=True, comment='离职原因'),
    sa.Column('handover_status', sa.String(length=16), server_default='待交接', nullable=False, comment='交接状态: 待交接, 交接中, 已完成'),
    sa.Column('notes', sa.String(length=512), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offboarding_date', 'offboarding_records', ['offboarding_date'], unique=False)
    op.create_index('ix_offboarding_employee_id', 'offboarding_records', ['employee_id'], unique=False)
    op.create_table('teams',
    sa.Column('name', sa.String(length=64), nullable=False, comment='班组名称'),
    sa.Column('code', sa.String(length=32), nullable=True, comment='班组编码'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='班组描述'),
    sa.Column('department_id', sa.Uuid(), nullable=False, comment='所属部门ID'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_department_id', 'teams', ['department_id'], unique=False)
    op.create_index('ix_teams_name', 'teams', ['name'], unique=False)
    op.create_table('calibration_plans',
    sa.Column('equipment_id', sa.Uuid(), nullable=False, comment='设备ID'),
    sa.Column('calibration_type', sa.String(length=20), nullable=False, comment='校准类型：内部校准/外部检定'),
    sa.Column('cycle_months', sa.Integer(), nullable=False, comment='校准周期（月）'),
    sa.Column('last_calibration_date', sa.Date(), nullable=True, comment='上次校准日期'),
    sa.Column('next_calibration_date', sa.Date(), nullable=True, comment='下次校准日期'),
    sa.Column('responsible_person_id', sa.Uuid(), nullable=True, comment='负责人ID'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='状态：启用/停用'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("calibration_type IN ('内部校准', '外部检定')", name='ck_calibration_plans_calibration_type'),
    sa.CheckConstraint("status IN ('启用', '停用')", name='ck_calibration_plans_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['responsible_person_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_orders',
    sa.Column('work_order_no', sa.String(length=50), nullable=False, comment='工单编号'),
    sa.Column('equipment_id', sa.Uuid(), nullable=False, comment='设备ID'),
    sa.Column('order_type', sa.String(length=20), nullable=False, comment='工单类型：故障维修/校准'),
    sa.Column('priority', sa.String(length=10), nullable=False, comment='优先级：紧急/高/中/低'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：待处理/已指派/维修中/待验收/已完成/已关闭'),
    sa.Column('fault_symptom_id', sa.Uuid(), nullable=True, comment='故障现象ID'),
    sa.Column('fault_cause_id', sa.Uuid(), nullable=True, comment='故障原因ID'),
    sa.Column('fault_action_id', sa.Uuid(), nullable=True, comment='维修措施ID'),
    sa.Column('fault_description', sa.Text(), nullable=True, comment='故障描述'),
    sa.Column('reporter_id', sa.Uuid(), nullable=False, comment='报修人ID'),
    sa.Column('assignee_id', sa.Uuid(), nullable=True, comment='指派人ID'),
    sa.Column('verified_by', sa.Uuid(), nullable=True, comment='验收人ID'),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='报修时间'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True, comment='指派时间'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始维修时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='验收时间'),
    sa.Column('verification_result', sa.String(length=10), nullable=True, comment='验收结果：合格/不合格'),
    sa.Column('verification_remark', sa.Text(), nullable=True, comment='验收备注'),
    sa.Column('repair_detail', sa.Text(), nullable=True, comment='维修详情'),
    sa.Column('actual_duration', sa.Integer(), nullable=True, comment='实际用时（分钟）'),
    sa.Column('original_equipment_status', sa.String(length=20), nullable=True, comment='创建工单时的设备原始状态'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("order_type IN ('故障维修', '校准')", name='ck_work_orders_order_type'),
    sa.CheckConstraint("priority IN ('紧急', '高', '中', '低')", name='ck_work_orders_priority'),
    sa.CheckConstraint("status IN ('待处理', '已指派', '维修中', '待验收', '已完成', '已关闭')", name='ck_work_orders_status'),
    sa.CheckConstraint("verification_result IS NULL OR verification_result IN ('合格', '不合格')", name='ck_work_orders_verification_result'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['fault_action_id'], ['failure_actions.id'], ),
    sa.ForeignKeyConstraint(['fault_cause_id'], ['failure_causes.id'], ),
    sa.ForeignKeyConstraint(['fault_symptom_id'], ['failure_symptoms.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_no', 'is_deleted', name='uq_work_orders_work_order_no')
    )
    op.create_table('calibration_records',
    sa.Column('calibration_plan_id', sa.Uuid(), nullable=False, comment='校准计划ID'),
    sa.Column('equipment_id', sa.Uuid(), nullable=False, comment='设备ID'),
    sa.Column('calibration_date', sa.Date(), nullable=False, comment='校准日期'),
    sa.Column('calibration_type', sa.String(length=20), nullable=False, comment='校准类型：内部校准/外部检定'),
    sa.Column('result', sa.String(length=10), nullable=False, comment='校准结果：合格/不合格'),
    sa.Column('certificate_no', sa.String(length=100), nullable=True, comment='证书编号'),
    sa.Column('calibrated_by', sa.String(length=200), nullable=True, comment='校准人/机构'),
    sa.Column('next_due_date', sa.Date(), nullable=False, comment='下次校准日期'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("calibration_type IN ('内部校准', '外部检定')", name='ck_calibration_records_calibration_type'),
    sa.CheckConstraint("result IN ('合格', '不合格')", name='ck_calibration_records_result'),
    sa.ForeignKeyConstraint(['calibration_plan_id'], ['calibration_plans.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calibration_records')
    op.drop_table('work_orders')
    op.drop_table('calibration_plans')
    op.drop_index('ix_teams_name', table_name='teams')
    op.drop_index('ix_teams_department_id', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_offboarding_employee_id', table_name='offboarding_records')
    op.drop_index('ix_offboarding_date', table_name='offboarding_records')
    op.drop_table('offboarding_records')
    op.drop_table('equipments')
    op.drop_index('idx_audit_logs_user_id', table_name='logs')
    op.drop_index('idx_audit_logs_resource', table_name='logs')
    op.drop_index('idx_audit_logs_request_id', table_name='logs')
    op.drop_index('idx_audit_logs_created_at', table_name='logs')
    op.drop_table('logs')
    op.drop_table('locations')
    op.drop_table('failure_symptoms')
    op.drop_table('failure_causes')
    op.drop_table('failure_actions')
    op.drop_table('equipment_categories')
    op.drop_index('ix_employees_status', table_name='employees')
    op.drop_index('ix_employees_feishu_record_id', table_name='employees')
    op.drop_index('ix_employees_employee_number', table_name='employees')
    op.drop_index('ix_employees_department', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_departments_code', table_name='departments')
    op.drop_table('departments')
    op.drop_table('users')
    # ### end Alembic commands ###
