"""add_training_ledgers_table

Revision ID: 2eeaf283689c
Revises: 7aeb32063768
Create Date: 2026-06-10 13:49:48.070352
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eeaf283689c'
down_revision: Union[str, None] = '7aeb32063768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_ledgers',
    sa.Column('employee_number', sa.String(length=32), nullable=False, comment='工号'),
    sa.Column('training_date', sa.Date(), nullable=False, comment='培训日期'),
    sa.Column('training_subject', sa.String(length=256), nullable=False, comment='培训课程/主题'),
    sa.Column('training_method', sa.String(length=32), nullable=True, comment='培训方式'),
    sa.Column('duration_hours', sa.Float(), nullable=True, comment='课时'),
    sa.Column('location', sa.String(length=128), nullable=True, comment='培训地点'),
    sa.Column('trainer', sa.String(length=128), nullable=True, comment='培训单位/培训师'),
    sa.Column('assessment_result', sa.String(length=16), nullable=True, comment='考核成绩'),
    sa.Column('source_type', sa.String(length=16), server_default='manual', nullable=False, comment='来源: manual手动, notification培训通知关联'),
    sa.Column('source_id', sa.String(length=64), nullable=True, comment='来源ID'),
    sa.Column('remarks', sa.String(length=512), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_training_ledgers_employee_number', 'training_ledgers', ['employee_number'], unique=False, schema='hr')
    op.create_index('ix_training_ledgers_training_date', 'training_ledgers', ['training_date'], unique=False, schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_ledgers_training_date', table_name='training_ledgers', schema='hr')
    op.drop_index('ix_training_ledgers_employee_number', table_name='training_ledgers', schema='hr')
    op.drop_table('training_ledgers', schema='hr')
    # ### end Alembic commands ###
