"""add maintenance tables

Revision ID: 32146cf65fa7
Revises: 3093dedbc980
Create Date: 2026-06-03 10:08:09.099483
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32146cf65fa7'
down_revision: Union[str, None] = '3093dedbc980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure_actions',
    sa.Column('code', sa.String(length=50), nullable=False, comment='维修措施代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='维修措施名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='维修措施描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'is_deleted', name='uq_failure_actions_code'),
    schema='equipment'
    )
    op.create_table('failure_causes',
    sa.Column('code', sa.String(length=50), nullable=False, comment='故障原因代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='故障原因名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='故障原因描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'is_deleted', name='uq_failure_causes_code'),
    schema='equipment'
    )
    op.create_table('failure_symptoms',
    sa.Column('code', sa.String(length=50), nullable=False, comment='故障现象代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='故障现象名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='故障现象描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'is_deleted', name='uq_failure_symptoms_code'),
    schema='equipment'
    )
    op.create_table('calibration_plans',
    sa.Column('equipment_id', sa.Uuid(), nullable=False, comment='设备ID'),
    sa.Column('calibration_type', sa.String(length=20), nullable=False, comment='校准类型：内部校准/外部检定'),
    sa.Column('cycle_months', sa.Integer(), nullable=False, comment='校准周期（月）'),
    sa.Column('last_calibration_date', sa.Date(), nullable=True, comment='上次校准日期'),
    sa.Column('next_calibration_date', sa.Date(), nullable=True, comment='下次校准日期'),
    sa.Column('responsible_person_id', sa.Uuid(), nullable=True, comment='负责人ID'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='状态：启用/停用'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("calibration_type IN ('内部校准', '外部检定')", name='ck_calibration_plans_calibration_type'),
    sa.CheckConstraint("status IN ('启用', '停用')", name='ck_calibration_plans_status'),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipments.id'], ),
    sa.ForeignKeyConstraint(['responsible_person_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equipment'
    )
    op.create_table('work_orders',
    sa.Column('work_order_no', sa.String(length=50), nullable=False, comment='工单编号'),
    sa.Column('equipment_id', sa.Uuid(), nullable=False, comment='设备ID'),
    sa.Column('order_type', sa.String(length=20), nullable=False, comment='工单类型：故障维修/校准'),
    sa.Column('priority', sa.String(length=10), nullable=False, comment='优先级：紧急/高/中/低'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：待处理/已指派/维修中/待验收/已完成/已关闭'),
    sa.Column('fault_symptom_id', sa.Uuid(), nullable=True, comment='故障现象ID'),
    sa.Column('fault_cause_id', sa.Uuid(), nullable=True, comment='故障原因ID'),
    sa.Column('fault_action_id', sa.Uuid(), nullable=True, comment='维修措施ID'),
    sa.Column('fault_description', sa.Text(), nullable=True, comment='故障描述'),
    sa.Column('reporter_id', sa.Uuid(), nullable=False, comment='报修人ID'),
    sa.Column('assignee_id', sa.Uuid(), nullable=True, comment='指派人ID'),
    sa.Column('verified_by', sa.Uuid(), nullable=True, comment='验收人ID'),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='报修时间'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True, comment='指派时间'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始维修时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='验收时间'),
    sa.Column('verification_result', sa.String(length=10), nullable=True, comment='验收结果：合格/不合格'),
    sa.Column('verification_remark', sa.Text(), nullable=True, comment='验收备注'),
    sa.Column('repair_detail', sa.Text(), nullable=True, comment='维修详情'),
    sa.Column('actual_duration', sa.Integer(), nullable=True, comment='实际用时（分钟）'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("order_type IN ('故障维修', '校准')", name='ck_work_orders_order_type'),
    sa.CheckConstraint("priority IN ('紧急', '高', '中', '低')", name='ck_work_orders_priority'),
    sa.CheckConstraint("status IN ('待处理', '已指派', '维修中', '待验收', '已完成', '已关闭')", name='ck_work_orders_status'),
    sa.CheckConstraint("verification_result IS NULL OR verification_result IN ('合格', '不合格')", name='ck_work_orders_verification_result'),
    sa.ForeignKeyConstraint(['assignee_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipments.id'], ),
    sa.ForeignKeyConstraint(['fault_action_id'], ['equipment.failure_actions.id'], ),
    sa.ForeignKeyConstraint(['fault_cause_id'], ['equipment.failure_causes.id'], ),
    sa.ForeignKeyConstraint(['fault_symptom_id'], ['equipment.failure_symptoms.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_no', 'is_deleted', name='uq_work_orders_work_order_no'),
    schema='equipment'
    )
    op.create_table('calibration_records',
    sa.Column('calibration_plan_id', sa.Uuid(), nullable=False, comment='校准计划ID'),
    sa.Column('equipment_id', sa.Uuid(), nullable=False, comment='设备ID'),
    sa.Column('calibration_date', sa.Date(), nullable=False, comment='校准日期'),
    sa.Column('calibration_type', sa.String(length=20), nullable=False, comment='校准类型：内部校准/外部检定'),
    sa.Column('result', sa.String(length=10), nullable=False, comment='校准结果：合格/不合格'),
    sa.Column('certificate_no', sa.String(length=100), nullable=True, comment='证书编号'),
    sa.Column('calibrated_by', sa.String(length=200), nullable=True, comment='校准人/机构'),
    sa.Column('next_due_date', sa.Date(), nullable=False, comment='下次校准日期'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("calibration_type IN ('内部校准', '外部检定')", name='ck_calibration_records_calibration_type'),
    sa.CheckConstraint("result IN ('合格', '不合格')", name='ck_calibration_records_result'),
    sa.ForeignKeyConstraint(['calibration_plan_id'], ['equipment.calibration_plans.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipments.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equipment'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calibration_records', schema='equipment')
    op.drop_table('work_orders', schema='equipment')
    op.drop_table('calibration_plans', schema='equipment')
    op.drop_table('failure_symptoms', schema='equipment')
    op.drop_table('failure_causes', schema='equipment')
    op.drop_table('failure_actions', schema='equipment')
    # ### end Alembic commands ###
