"""add is_critical to special_operation_reports

Revision ID: 3fbb2904cf43
Revises: 118b4228c2e7
Create Date: 2026-06-06 16:14:39.392224
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fbb2904cf43'
down_revision: Union[str, None] = '118b4228c2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_collect_logs',
    sa.Column('platform_code', sa.String(length=50), nullable=False, comment='采集的平台'),
    sa.Column('collect_time', sa.DateTime(timezone=True), nullable=False, comment='采集触发时间'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: success/partial/failed'),
    sa.Column('device_count', sa.Integer(), nullable=False, comment='应采集设备数'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='成功条数'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='energy'
    )
    op.create_table('energy_data',
    sa.Column('device_config_id', sa.UUID(), nullable=False, comment='设备配置ID'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='数据时间点(小时粒度)'),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False, comment='能耗累计值'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='计量单位'),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='实际采集时间'),
    sa.Column('platform_raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='原始返回数据'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_config_id', 'timestamp', name='uq_energy_data_device_timestamp'),
    schema='energy'
    )
    op.create_table('energy_device_configs',
    sa.Column('platform_code', sa.String(length=50), nullable=False, comment='平台标识'),
    sa.Column('platform_device_code', sa.String(length=100), nullable=False, comment='三方平台设备/采集点编码'),
    sa.Column('device_name', sa.String(length=200), nullable=False, comment='设备名称'),
    sa.Column('energy_type', sa.String(length=20), nullable=False, comment='能源类型: electricity/steam/water'),
    sa.Column('api_endpoint', sa.String(length=500), nullable=False, comment='API 路径'),
    sa.Column('workshop', sa.String(length=100), nullable=False, comment='所属车间'),
    sa.Column('production_line', sa.String(length=100), nullable=False, comment='所属产线'),
    sa.Column('monitor_level', sa.String(length=20), nullable=False, comment='监控等级'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='计量单位'),
    sa.Column('collection_interval', sa.Integer(), nullable=False, comment='采集间隔(分钟)'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用采集'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("energy_type IN ('electricity', 'steam', 'water')", name='ck_energy_device_config_energy_type'),
    sa.CheckConstraint("monitor_level IN ('normal', 'important', 'urgent')", name='ck_energy_device_config_monitor_level'),
    sa.CheckConstraint('collection_interval > 0', name='ck_energy_device_config_interval_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_code', 'platform_device_code', 'is_deleted', name='uq_energy_device_config_platform_device'),
    schema='energy'
    )
    op.create_table('maintenance_config',
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('config_value', sa.String(length=500), nullable=False, comment='配置值'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key'),
    schema='equipment'
    )
    op.create_table('spare_parts',
    sa.Column('code', sa.String(length=50), nullable=False, comment='备件编码'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='备件名称'),
    sa.Column('specification', sa.String(length=200), nullable=True, comment='规格型号'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='计量单位'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='备件分类'),
    sa.Column('default_supplier', sa.String(length=200), nullable=True, comment='默认供应商'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='参考单价'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'is_deleted', name='uq_spare_parts_code'),
    schema='equipment'
    )
    op.create_table('inspection_templates',
    sa.Column('name', sa.String(length=200), nullable=False, comment='模板名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='模板描述'),
    sa.Column('equipment_category_id', sa.Uuid(), nullable=True, comment='适用设备分类ID'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['equipment_category_id'], ['equipment.equipment_categories.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equipment'
    )
    op.create_table('spare_part_stocks',
    sa.Column('spare_part_id', sa.Uuid(), nullable=False, comment='备件ID'),
    sa.Column('warehouse_location', sa.String(length=100), nullable=True, comment='库位'),
    sa.Column('current_qty', sa.Integer(), server_default='0', nullable=False, comment='当前库存'),
    sa.Column('safety_qty', sa.Integer(), server_default='0', nullable=False, comment='安全库存'),
    sa.Column('min_order_qty', sa.Integer(), server_default='1', nullable=False, comment='最小采购批量'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['spare_part_id'], ['equipment.spare_parts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spare_part_id'),
    schema='equipment'
    )
    op.create_table('equipment_spare_parts',
    sa.Column('equipment_id', sa.Uuid(), nullable=False, comment='设备ID'),
    sa.Column('spare_part_id', sa.Uuid(), nullable=False, comment='备件ID'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='该设备需要的数量'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipments.id'], ),
    sa.ForeignKeyConstraint(['spare_part_id'], ['equipment.spare_parts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id', 'spare_part_id', 'is_deleted', name='uq_equipment_spare_parts_eq_sp'),
    schema='equipment'
    )
    op.create_table('inspection_template_items',
    sa.Column('template_id', sa.Uuid(), nullable=False, comment='模板ID'),
    sa.Column('item_name', sa.String(length=200), nullable=False, comment='检查项名称'),
    sa.Column('item_description', sa.Text(), nullable=True, comment='检查项说明'),
    sa.Column('expected_result', sa.String(length=200), nullable=True, comment='预期结果/标准值'),
    sa.Column('check_method', sa.String(length=100), nullable=True, comment='检查方法'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序序号'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['equipment.inspection_templates.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equipment'
    )
    op.create_table('maintenance_plans',
    sa.Column('equipment_id', sa.Uuid(), nullable=False, comment='设备ID'),
    sa.Column('plan_name', sa.String(length=200), nullable=False, comment='计划名称'),
    sa.Column('plan_type', sa.String(length=20), nullable=False, comment='计划类型：预防性维护/预测性维护'),
    sa.Column('frequency', sa.Integer(), nullable=False, comment='维护频率数值'),
    sa.Column('frequency_unit', sa.String(length=10), nullable=False, comment='频率单位：天/周/月/年'),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True, comment='上次维护日期'),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True, comment='下次维护日期'),
    sa.Column('responsible_person_id', sa.Uuid(), nullable=True, comment='负责人ID'),
    sa.Column('maintenance_content', sa.Text(), nullable=True, comment='维护内容说明'),
    sa.Column('status', sa.String(length=10), server_default='启用', nullable=False, comment='状态：启用/停用/已完成'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("frequency_unit IN ('天', '周', '月', '年')", name='ck_maintenance_plans_frequency_unit'),
    sa.CheckConstraint("plan_type IN ('预防性维护', '预测性维护')", name='ck_maintenance_plans_plan_type'),
    sa.CheckConstraint("status IN ('启用', '停用', '已完成')", name='ck_maintenance_plans_status'),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipments.id'], ),
    sa.ForeignKeyConstraint(['responsible_person_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equipment'
    )
    op.create_table('inspection_records',
    sa.Column('work_order_id', sa.Uuid(), nullable=False, comment='关联巡检工单ID'),
    sa.Column('template_item_id', sa.Uuid(), nullable=False, comment='检查项ID'),
    sa.Column('result', sa.String(length=20), nullable=False, comment='结果：正常/异常/跳过'),
    sa.Column('actual_value', sa.String(length=200), nullable=True, comment='实际值'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['template_item_id'], ['equipment.inspection_template_items.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['equipment.work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equipment'
    )
    op.create_table('spare_part_transactions',
    sa.Column('spare_part_id', sa.Uuid(), nullable=False, comment='备件ID'),
    sa.Column('work_order_id', sa.Uuid(), nullable=True, comment='关联工单ID'),
    sa.Column('transaction_type', sa.String(length=20), nullable=False, comment='类型：入库/出库/盘点调整'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量（正=入库，负=出库）'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("transaction_type IN ('入库', '出库', '盘点调整')", name='ck_spare_part_transactions_type'),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['spare_part_id'], ['equipment.spare_parts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['equipment.work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equipment'
    )
    op.create_table('work_order_images',
    sa.Column('work_order_id', sa.Uuid(), nullable=False, comment='工单ID'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='服务器文件路径'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='上传时间'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['equipment.work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equipment'
    )
    op.add_column('equipments', sa.Column('warranty_expire_date', sa.Date(), nullable=True, comment='保修到期日'), schema='equipment')
    op.add_column('equipments', sa.Column('asset_value', sa.Float(), nullable=True, comment='资产原值（元）'), schema='equipment')
    op.add_column('equipments', sa.Column('depreciation_years', sa.Integer(), nullable=True, comment='折旧年限'), schema='equipment')
    op.add_column('equipments', sa.Column('technical_params', sa.JSON(), nullable=True, comment='技术参数（JSON）'), schema='equipment')
    op.add_column('work_orders', sa.Column('maintenance_plan_id', sa.Uuid(), nullable=True, comment='关联维护计划ID'), schema='equipment')
    op.add_column('work_orders', sa.Column('planned_start_date', sa.Date(), nullable=True, comment='计划执行日期'), schema='equipment')
    op.add_column('work_orders', sa.Column('checklist_template_id', sa.Uuid(), nullable=True, comment='关联巡检模板ID'), schema='equipment')
    op.add_column('work_orders', sa.Column('check_result', sa.String(length=20), nullable=True, comment='巡检结果：正常/异常'), schema='equipment')
    op.add_column('work_orders', sa.Column('spare_parts_cost', sa.Float(), nullable=True, comment='备件费用汇总'), schema='equipment')
    op.create_foreign_key(None, 'work_orders', 'inspection_templates', ['checklist_template_id'], ['id'], source_schema='equipment', referent_schema='equipment')
    op.create_foreign_key(None, 'work_orders', 'maintenance_plans', ['maintenance_plan_id'], ['id'], source_schema='equipment', referent_schema='equipment')
    op.add_column('special_operation_reports', sa.Column('is_critical', sa.Boolean(), server_default='false', nullable=False, comment='是否关键作业（AI自动判定+可手动修改）'), schema='safety')
    op.add_column('special_operation_reports', sa.Column('is_critical_reason', sa.Text(), nullable=True, comment='关键作业判定理由'), schema='safety')
    op.add_column('special_operation_reports', sa.Column('is_critical_updated_by', sa.String(length=100), nullable=True, comment='手动修改关键作业标记的操作人'), schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('special_operation_reports', 'is_critical_updated_by', schema='safety')
    op.drop_column('special_operation_reports', 'is_critical_reason', schema='safety')
    op.drop_column('special_operation_reports', 'is_critical', schema='safety')
    op.drop_constraint(None, 'work_orders', schema='equipment', type_='foreignkey')
    op.drop_constraint(None, 'work_orders', schema='equipment', type_='foreignkey')
    op.drop_column('work_orders', 'spare_parts_cost', schema='equipment')
    op.drop_column('work_orders', 'check_result', schema='equipment')
    op.drop_column('work_orders', 'checklist_template_id', schema='equipment')
    op.drop_column('work_orders', 'planned_start_date', schema='equipment')
    op.drop_column('work_orders', 'maintenance_plan_id', schema='equipment')
    op.drop_column('equipments', 'technical_params', schema='equipment')
    op.drop_column('equipments', 'depreciation_years', schema='equipment')
    op.drop_column('equipments', 'asset_value', schema='equipment')
    op.drop_column('equipments', 'warranty_expire_date', schema='equipment')
    op.drop_table('work_order_images', schema='equipment')
    op.drop_table('spare_part_transactions', schema='equipment')
    op.drop_table('inspection_records', schema='equipment')
    op.drop_table('maintenance_plans', schema='equipment')
    op.drop_table('inspection_template_items', schema='equipment')
    op.drop_table('equipment_spare_parts', schema='equipment')
    op.drop_table('spare_part_stocks', schema='equipment')
    op.drop_table('inspection_templates', schema='equipment')
    op.drop_table('spare_parts', schema='equipment')
    op.drop_table('maintenance_config', schema='equipment')
    op.drop_table('energy_device_configs', schema='energy')
    op.drop_table('energy_data', schema='energy')
    op.drop_table('energy_collect_logs', schema='energy')
    # ### end Alembic commands ###
