"""dossier_writer_restore_fk_constraints

Revision ID: 48bece2344cf
Revises: be0d4d96cdda
Create Date: 2026-06-30 11:38:00
"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '48bece2344cf'
down_revision: str | None = 'be0d4d96cdda'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'asset_page_splits', 'chapter_assets', ['asset_id'], ['id'], source_schema='dossier_writer', referent_schema='dossier_writer', ondelete='CASCADE')
    op.create_foreign_key(None, 'chapter_assets', 'users', ['updated_by'], ['id'], source_schema='dossier_writer', referent_schema='identity')
    op.create_foreign_key(None, 'chapter_assets', 'users', ['created_by'], ['id'], source_schema='dossier_writer', referent_schema='identity')
    op.create_foreign_key(None, 'chapter_assets', 'asset_categories', ['category_id'], ['id'], source_schema='dossier_writer', referent_schema='dossier_writer', ondelete='SET NULL')
    op.create_foreign_key(None, 'chapter_assets', 'dossier_chapters', ['chapter_id'], ['id'], source_schema='dossier_writer', referent_schema='dossier_writer', ondelete='CASCADE')
    op.create_foreign_key(None, 'dossier_chapters', 'users', ['updated_by'], ['id'], source_schema='dossier_writer', referent_schema='identity')
    op.create_foreign_key(None, 'dossier_chapters', 'product_dossiers', ['product_dossier_id'], ['id'], source_schema='dossier_writer', referent_schema='dossier_writer', ondelete='CASCADE')
    op.create_foreign_key(None, 'dossier_chapters', 'dossier_chapters', ['parent_id'], ['id'], source_schema='dossier_writer', referent_schema='dossier_writer', ondelete='CASCADE')
    op.create_foreign_key(None, 'dossier_chapters', 'users', ['created_by'], ['id'], source_schema='dossier_writer', referent_schema='identity')
    op.create_foreign_key(None, 'dossier_templates', 'users', ['created_by'], ['id'], source_schema='dossier_writer', referent_schema='identity')
    op.create_foreign_key(None, 'dossier_templates', 'users', ['updated_by'], ['id'], source_schema='dossier_writer', referent_schema='identity')
    op.create_foreign_key(None, 'dossier_templates', 'product_dossiers', ['product_dossier_id'], ['id'], source_schema='dossier_writer', referent_schema='dossier_writer', ondelete='CASCADE')
    op.create_foreign_key(None, 'field_fill_results', 'product_dossiers', ['dossier_id'], ['id'], source_schema='dossier_writer', referent_schema='dossier_writer', ondelete='CASCADE')
    op.create_foreign_key(None, 'field_fill_results', 'chapter_assets', ['source_asset_id'], ['id'], source_schema='dossier_writer', referent_schema='dossier_writer', ondelete='SET NULL')
    op.create_foreign_key(None, 'field_fill_results', 'dossier_chapters', ['chapter_id'], ['id'], source_schema='dossier_writer', referent_schema='dossier_writer', ondelete='CASCADE')
    op.create_foreign_key(None, 'field_fill_results', 'field_mappings', ['field_mapping_id'], ['id'], source_schema='dossier_writer', referent_schema='dossier_writer', ondelete='CASCADE')
    op.create_foreign_key(None, 'product_dossiers', 'users', ['updated_by'], ['id'], source_schema='dossier_writer', referent_schema='identity')
    op.create_foreign_key(None, 'product_dossiers', 'users', ['created_by'], ['id'], source_schema='dossier_writer', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_dossiers', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'product_dossiers', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'field_fill_results', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'field_fill_results', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'field_fill_results', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'field_fill_results', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'dossier_templates', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'dossier_templates', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'dossier_templates', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'dossier_chapters', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'dossier_chapters', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'dossier_chapters', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'dossier_chapters', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'chapter_assets', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'chapter_assets', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'chapter_assets', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'chapter_assets', schema='dossier_writer', type_='foreignkey')
    op.drop_constraint(None, 'asset_page_splits', schema='dossier_writer', type_='foreignkey')
    # ### end Alembic commands ###
