"""add_training_management_tables

Revision ID: 494e3004c6fe
Revises: 2eba70488232
Create Date: 2026-06-08 23:31:43.968786
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494e3004c6fe'
down_revision: Union[str, None] = '2eba70488232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_plans',
    sa.Column('plan_name', sa.String(length=128), nullable=False, comment='培训计划名称'),
    sa.Column('training_type', sa.String(length=16), server_default='新入职', nullable=False, comment='培训类型: 新入职, 调岗, 复工'),
    sa.Column('target_departments', sa.JSON(), nullable=True, comment='目标部门列表'),
    sa.Column('target_positions', sa.JSON(), nullable=True, comment='目标岗位列表'),
    sa.Column('planned_start_date', sa.Date(), nullable=True, comment='计划开始日期'),
    sa.Column('planned_end_date', sa.Date(), nullable=True, comment='计划结束日期'),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False, comment='状态: draft, approved, rejected, cancelled'),
    sa.Column('approver_name', sa.String(length=64), nullable=True, comment='审批人姓名'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='审批时间'),
    sa.Column('approval_remarks', sa.String(length=512), nullable=True, comment='审批备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_training_plans_status', 'training_plans', ['status'], unique=False, schema='hr')
    op.create_index('ix_training_plans_training_type', 'training_plans', ['training_type'], unique=False, schema='hr')
    op.create_table('training_assessments',
    sa.Column('plan_id', sa.Uuid(), nullable=False, comment='培训计划ID'),
    sa.Column('employee_id', sa.Uuid(), nullable=False, comment='员工ID'),
    sa.Column('assessment_date', sa.Date(), nullable=True, comment='考核日期'),
    sa.Column('assessment_type', sa.String(length=16), server_default='综合', nullable=False, comment='考核类型: 理论, 实操, 综合'),
    sa.Column('score', sa.Integer(), nullable=True, comment='得分'),
    sa.Column('max_score', sa.Integer(), nullable=True, comment='满分'),
    sa.Column('result', sa.String(length=8), server_default='待考核', nullable=False, comment='考核结果: 合格, 不合格, 待考核'),
    sa.Column('assessor_name', sa.String(length=64), nullable=True, comment='考核人姓名'),
    sa.Column('remarks', sa.String(length=512), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['hr.employees.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['hr.training_plans.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_training_assessments_employee_id', 'training_assessments', ['employee_id'], unique=False, schema='hr')
    op.create_index('ix_training_assessments_plan_id', 'training_assessments', ['plan_id'], unique=False, schema='hr')
    op.create_index('ix_training_assessments_result', 'training_assessments', ['result'], unique=False, schema='hr')
    op.create_table('training_plan_sops',
    sa.Column('plan_id', sa.Uuid(), nullable=False, comment='所属培训计划ID'),
    sa.Column('sop_name', sa.String(length=128), nullable=False, comment='SOP名称'),
    sa.Column('sop_code', sa.String(length=32), nullable=True, comment='SOP编号'),
    sa.Column('description', sa.Text(), nullable=True, comment='SOP描述'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='培训时长(分钟)'),
    sa.Column('version', sa.String(length=16), nullable=True, comment='版本号'),
    sa.Column('file_url', sa.String(length=512), nullable=True, comment='文件链接'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['hr.training_plans.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_training_plan_sops_plan_id', 'training_plan_sops', ['plan_id'], unique=False, schema='hr')
    op.create_table('training_approvals',
    sa.Column('plan_id', sa.Uuid(), nullable=False, comment='培训计划ID'),
    sa.Column('employee_id', sa.Uuid(), nullable=False, comment='员工ID'),
    sa.Column('assessment_id', sa.Uuid(), nullable=True, comment='关联考核ID'),
    sa.Column('approval_status', sa.String(length=16), server_default='pending', nullable=False, comment='审批状态: pending, approved, rejected'),
    sa.Column('approver_name', sa.String(length=64), nullable=True, comment='审批人姓名'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='审批时间'),
    sa.Column('approval_remarks', sa.String(length=512), nullable=True, comment='审批备注'),
    sa.Column('is_qualified', sa.Boolean(), nullable=True, comment='是否合格上岗'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['hr.training_assessments.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['hr.employees.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['hr.training_plans.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_training_approvals_approval_status', 'training_approvals', ['approval_status'], unique=False, schema='hr')
    op.create_index('ix_training_approvals_employee_id', 'training_approvals', ['employee_id'], unique=False, schema='hr')
    op.create_index('ix_training_approvals_plan_id', 'training_approvals', ['plan_id'], unique=False, schema='hr')
    op.create_table('training_records',
    sa.Column('plan_id', sa.Uuid(), nullable=False, comment='培训计划ID'),
    sa.Column('sop_id', sa.Uuid(), nullable=True, comment='SOP ID'),
    sa.Column('employee_id', sa.Uuid(), nullable=False, comment='员工ID'),
    sa.Column('training_date', sa.Date(), nullable=True, comment='培训日期'),
    sa.Column('trainer_name', sa.String(length=64), nullable=True, comment='培训师姓名'),
    sa.Column('training_location', sa.String(length=128), nullable=True, comment='培训地点'),
    sa.Column('completion_status', sa.String(length=16), server_default='未开始', nullable=False, comment='完成状态: 未开始, 进行中, 已完成, 缺席'),
    sa.Column('signature_image_url', sa.String(length=512), nullable=True, comment='员工签名图片URL'),
    sa.Column('remarks', sa.String(length=512), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['hr.employees.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['hr.training_plans.id'], ),
    sa.ForeignKeyConstraint(['sop_id'], ['hr.training_plan_sops.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_training_records_completion_status', 'training_records', ['completion_status'], unique=False, schema='hr')
    op.create_index('ix_training_records_employee_id', 'training_records', ['employee_id'], unique=False, schema='hr')
    op.create_index('ix_training_records_plan_id', 'training_records', ['plan_id'], unique=False, schema='hr')
    op.drop_constraint(op.f('onboarding_records_employee_number_key'), 'onboarding_records', schema='hr', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('onboarding_records_employee_number_key'), 'onboarding_records', ['employee_number'], schema='hr', postgresql_nulls_not_distinct=False)
    op.drop_index('ix_training_records_plan_id', table_name='training_records', schema='hr')
    op.drop_index('ix_training_records_employee_id', table_name='training_records', schema='hr')
    op.drop_index('ix_training_records_completion_status', table_name='training_records', schema='hr')
    op.drop_table('training_records', schema='hr')
    op.drop_index('ix_training_approvals_plan_id', table_name='training_approvals', schema='hr')
    op.drop_index('ix_training_approvals_employee_id', table_name='training_approvals', schema='hr')
    op.drop_index('ix_training_approvals_approval_status', table_name='training_approvals', schema='hr')
    op.drop_table('training_approvals', schema='hr')
    op.drop_index('ix_training_plan_sops_plan_id', table_name='training_plan_sops', schema='hr')
    op.drop_table('training_plan_sops', schema='hr')
    op.drop_index('ix_training_assessments_result', table_name='training_assessments', schema='hr')
    op.drop_index('ix_training_assessments_plan_id', table_name='training_assessments', schema='hr')
    op.drop_index('ix_training_assessments_employee_id', table_name='training_assessments', schema='hr')
    op.drop_table('training_assessments', schema='hr')
    op.drop_index('ix_training_plans_training_type', table_name='training_plans', schema='hr')
    op.drop_index('ix_training_plans_status', table_name='training_plans', schema='hr')
    op.drop_table('training_plans', schema='hr')
    # ### end Alembic commands ###
