"""enhance_hazard_report_and_safety_check

Revision ID: 63e0261d5871
Revises: fb2c920c3d32
Create Date: 2026-06-04 14:41:40.835681
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63e0261d5871'
down_revision: Union[str, None] = 'fb2c920c3d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hazard_revision_archives',
    sa.Column('regulation_name', sa.String(length=255), nullable=False, comment='对应的操规名称'),
    sa.Column('hazard_document_path', sa.String(length=500), nullable=True, comment='最新危险源辨识文档路径'),
    sa.Column('hazard_document_original_name', sa.String(length=255), nullable=True, comment='文档原始文件名'),
    sa.Column('identification_date', sa.DateTime(timezone=True), nullable=False, comment='最后辨识日期'),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False, comment='状态: active/archived'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    op.create_table('operation_regulations',
    sa.Column('regulation_no', sa.String(length=64), nullable=False, comment='操规编号'),
    sa.Column('regulation_name', sa.String(length=255), nullable=False, comment='操规名称'),
    sa.Column('document_path', sa.String(length=500), nullable=True, comment='操规文档路径（当前最新版本）'),
    sa.Column('document_original_name', sa.String(length=255), nullable=True, comment='文档原始文件名'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='岗位（达托/达巴，逗号分隔）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regulation_no', name='uq_operation_regulations_no'),
    schema='safety'
    )
    op.create_table('regulation_revisions',
    sa.Column('revision_no', sa.String(length=64), nullable=False, comment='修订编号'),
    sa.Column('regulation_id', sa.UUID(), nullable=False, comment='关联操规ID'),
    sa.Column('regulation_name', sa.String(length=255), nullable=False, comment='安全操规名称'),
    sa.Column('old_document_path', sa.String(length=500), nullable=True, comment='旧文档路径'),
    sa.Column('reviser', sa.UUID(), nullable=True, comment='修订人'),
    sa.Column('reviser_name', sa.String(length=100), nullable=True, comment='修订人姓名'),
    sa.Column('revision_time', sa.DateTime(timezone=True), nullable=False, comment='修订时间'),
    sa.Column('revision_type', sa.String(length=32), server_default='manual', nullable=False, comment='修订类型: manual/ai'),
    sa.Column('revision_opinion', sa.Text(), nullable=True, comment='修订意见/内容'),
    sa.Column('revision_scope', sa.String(length=100), nullable=True, comment='修订范围（逗号分隔: process/safety_requirement）'),
    sa.Column('review_opinion', sa.String(length=32), server_default='pending', nullable=False, comment='审核意见: pending/approved'),
    sa.Column('new_document_path', sa.String(length=500), nullable=True, comment='新文档路径'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['regulation_id'], ['safety.operation_regulations.id'], ),
    sa.ForeignKeyConstraint(['reviser'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_no', name='uq_regulation_revisions_no'),
    schema='safety'
    )
    op.create_table('hazard_revision_records',
    sa.Column('hazard_revision_no', sa.String(length=64), nullable=False, comment='危险源辨识修订编号'),
    sa.Column('regulation_revision_id', sa.UUID(), nullable=True, comment='关联操规修订记录ID'),
    sa.Column('regulation_name', sa.String(length=255), nullable=False, comment='对应的操规名称'),
    sa.Column('identifier_id', sa.UUID(), nullable=True, comment='辨识人'),
    sa.Column('identifier_name', sa.String(length=100), nullable=True, comment='辨识人姓名'),
    sa.Column('identification_time', sa.DateTime(timezone=True), nullable=False, comment='辨识时间'),
    sa.Column('identification_type', sa.String(length=32), server_default='auto_trigger', nullable=False, comment='辨识类型: auto_trigger/manual_start'),
    sa.Column('process_change_content', sa.Text(), nullable=True, comment='涉及工艺变更内容'),
    sa.Column('identification_scope', sa.String(length=200), nullable=True, comment='辨识范围（逗号分隔: 人/机/料/法/环）'),
    sa.Column('review_opinion', sa.String(length=32), server_default='pending', nullable=False, comment='审核意见: pending/approved/rejected'),
    sa.Column('hazard_document_path', sa.String(length=500), nullable=True, comment='危险源辨识文档路径'),
    sa.Column('hazard_document_original_name', sa.String(length=255), nullable=True, comment='文档原始文件名'),
    sa.Column('linked_hazard_archive_id', sa.UUID(), nullable=True, comment='关联的危险源辨识存档ID'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['identifier_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['linked_hazard_archive_id'], ['safety.hazard_revision_archives.id'], ),
    sa.ForeignKeyConstraint(['regulation_revision_id'], ['safety.regulation_revisions.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hazard_revision_no', name='uq_hazard_revision_records_no'),
    schema='safety'
    )
    op.add_column('hazard_reports', sa.Column('hazard_category', sa.String(length=32), nullable=True, comment='隐患类别（设备设施/危化储存…）'), schema='safety')
    op.add_column('hazard_reports', sa.Column('major_hazard_basis', sa.Text(), nullable=True, comment='重大隐患判定依据'), schema='safety')
    op.add_column('hazard_reports', sa.Column('key_defect', sa.String(length=100), nullable=True, comment='重点缺陷'), schema='safety')
    op.add_column('hazard_reports', sa.Column('defect_photos', sa.Text(), nullable=True, comment='缺陷图片JSON数组'), schema='safety')
    op.add_column('hazard_reports', sa.Column('rectification_responsible_person', sa.UUID(), nullable=True, comment='整改责任人'), schema='safety')
    op.add_column('hazard_reports', sa.Column('rectification_responsible_person_name', sa.String(length=100), nullable=True, comment='整改责任人姓名'), schema='safety')
    op.add_column('hazard_reports', sa.Column('rectification_responsible_department', sa.String(length=100), nullable=True, comment='整改责任人部门'), schema='safety')
    op.add_column('hazard_reports', sa.Column('corrective_preventive_measures', sa.Text(), nullable=True, comment='纠正预防措施'), schema='safety')
    op.add_column('hazard_reports', sa.Column('planned_completion_date', sa.DateTime(timezone=True), nullable=True, comment='计划完成时间'), schema='safety')
    op.add_column('hazard_reports', sa.Column('actual_completion_date', sa.DateTime(timezone=True), nullable=True, comment='实际完成时间'), schema='safety')
    op.add_column('hazard_reports', sa.Column('extended_deadline', sa.DateTime(timezone=True), nullable=True, comment='延期完成日期'), schema='safety')
    op.add_column('hazard_reports', sa.Column('rectification_photos', sa.Text(), nullable=True, comment='整改后图片JSON数组'), schema='safety')
    op.alter_column('hazard_reports', 'hazard_type',
               existing_type=sa.VARCHAR(length=32),
               comment='隐患分类（人/物/环/管）',
               existing_comment='隐患类型',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_level',
               existing_type=sa.VARCHAR(length=16),
               comment='隐患等级（一般/较大/重大）',
               existing_comment='隐患等级',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='计划完成时间',
               existing_comment='整改期限',
               existing_nullable=True,
               schema='safety')
    op.create_foreign_key(None, 'hazard_reports', 'users', ['rectification_responsible_person'], ['id'], source_schema='safety', referent_schema='identity')
    op.add_column('safety_checks', sa.Column('inspector_confirmed', sa.Boolean(), server_default='false', nullable=False, comment='检查人员确认'), schema='safety')
    op.add_column('safety_checks', sa.Column('safety_officer_confirmed', sa.Boolean(), server_default='false', nullable=False, comment='安全办确认'), schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('safety_checks', 'safety_officer_confirmed', schema='safety')
    op.drop_column('safety_checks', 'inspector_confirmed', schema='safety')
    op.drop_constraint(None, 'hazard_reports', schema='safety', type_='foreignkey')
    op.alter_column('hazard_reports', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='整改期限',
               existing_comment='计划完成时间',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_level',
               existing_type=sa.VARCHAR(length=16),
               comment='隐患等级',
               existing_comment='隐患等级（一般/较大/重大）',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_type',
               existing_type=sa.VARCHAR(length=32),
               comment='隐患类型',
               existing_comment='隐患分类（人/物/环/管）',
               existing_nullable=False,
               schema='safety')
    op.drop_column('hazard_reports', 'rectification_photos', schema='safety')
    op.drop_column('hazard_reports', 'extended_deadline', schema='safety')
    op.drop_column('hazard_reports', 'actual_completion_date', schema='safety')
    op.drop_column('hazard_reports', 'planned_completion_date', schema='safety')
    op.drop_column('hazard_reports', 'corrective_preventive_measures', schema='safety')
    op.drop_column('hazard_reports', 'rectification_responsible_department', schema='safety')
    op.drop_column('hazard_reports', 'rectification_responsible_person_name', schema='safety')
    op.drop_column('hazard_reports', 'rectification_responsible_person', schema='safety')
    op.drop_column('hazard_reports', 'defect_photos', schema='safety')
    op.drop_column('hazard_reports', 'key_defect', schema='safety')
    op.drop_column('hazard_reports', 'major_hazard_basis', schema='safety')
    op.drop_column('hazard_reports', 'hazard_category', schema='safety')
    op.drop_table('hazard_revision_records', schema='safety')
    op.drop_table('regulation_revisions', schema='safety')
    op.drop_table('operation_regulations', schema='safety')
    op.drop_table('hazard_revision_archives', schema='safety')
    # ### end Alembic commands ###
