"""add administration vehicle and it ticket tables

Revision ID: 65acf67e248f
Revises: ec4654a030c0
Create Date: 2026-06-06 18:50:56.924935
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65acf67e248f'
down_revision: Union[str, None] = 'ec4654a030c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('it_service_tickets',
    sa.Column('ticket_no', sa.String(length=32), nullable=False, comment='工单编号'),
    sa.Column('requester_name', sa.String(length=64), nullable=False, comment='报障人姓名'),
    sa.Column('requester_department', sa.String(length=64), nullable=True, comment='报障人部门'),
    sa.Column('requester_phone', sa.String(length=32), nullable=True, comment='联系电话'),
    sa.Column('ticket_type', sa.String(length=32), nullable=False, comment='工单类型: 硬件故障, 软件问题, 网络问题, 账号权限, 其他'),
    sa.Column('priority', sa.String(length=16), server_default='中', nullable=False, comment='优先级: 低, 中, 高, 紧急'),
    sa.Column('title', sa.String(length=128), nullable=False, comment='问题标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='问题描述'),
    sa.Column('status', sa.String(length=16), server_default='待处理', nullable=False, comment='状态: 待处理, 处理中, 已解决, 已关闭'),
    sa.Column('assigned_to', sa.String(length=64), nullable=True, comment='指派给'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='解决时间'),
    sa.Column('solution', sa.Text(), nullable=True, comment='解决方案'),
    sa.Column('feishu_record_id', sa.String(length=32), nullable=True, comment='飞书多维表格 record_id'),
    sa.Column('feishu_synced_at', sa.DateTime(), nullable=True, comment='上次飞书同步时间'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_no'),
    schema='administration'
    )
    op.create_index('ix_it_tickets_requester', 'it_service_tickets', ['requester_name'], unique=False, schema='administration')
    op.create_index('ix_it_tickets_status', 'it_service_tickets', ['status'], unique=False, schema='administration')
    op.create_index('ix_it_tickets_type', 'it_service_tickets', ['ticket_type'], unique=False, schema='administration')
    op.create_table('vehicles',
    sa.Column('plate_number', sa.String(length=32), nullable=False, comment='车牌号'),
    sa.Column('brand', sa.String(length=64), nullable=True, comment='品牌'),
    sa.Column('model', sa.String(length=64), nullable=True, comment='型号'),
    sa.Column('color', sa.String(length=32), nullable=True, comment='颜色'),
    sa.Column('purchase_date', sa.Date(), nullable=True, comment='购买日期'),
    sa.Column('mileage', sa.Integer(), nullable=True, comment='行驶里程'),
    sa.Column('status', sa.String(length=16), server_default='可用', nullable=False, comment='状态: 可用, 维修中, 已报废'),
    sa.Column('owner_department', sa.String(length=64), nullable=True, comment='所属部门'),
    sa.Column('feishu_record_id', sa.String(length=32), nullable=True, comment='飞书多维表格 record_id'),
    sa.Column('feishu_synced_at', sa.DateTime(), nullable=True, comment='上次飞书同步时间'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number'),
    schema='administration'
    )
    op.create_index('ix_vehicles_plate_number', 'vehicles', ['plate_number'], unique=False, schema='administration')
    op.create_index('ix_vehicles_status', 'vehicles', ['status'], unique=False, schema='administration')
    op.create_table('vehicle_requests',
    sa.Column('applicant_name', sa.String(length=64), nullable=False, comment='申请人姓名'),
    sa.Column('applicant_department', sa.String(length=64), nullable=True, comment='申请人部门'),
    sa.Column('applicant_phone', sa.String(length=32), nullable=True, comment='联系电话'),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True, comment='分配车辆ID'),
    sa.Column('purpose', sa.Text(), nullable=False, comment='用车事由'),
    sa.Column('destination', sa.String(length=256), nullable=True, comment='目的地'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('passengers', sa.Integer(), nullable=True, comment='乘车人数'),
    sa.Column('status', sa.String(length=16), server_default='待审批', nullable=False, comment='状态: 待审批, 已通过, 已拒绝, 已完成'),
    sa.Column('approver', sa.String(length=64), nullable=True, comment='审批人'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='审批时间'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['administration.vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='administration'
    )
    op.create_index('ix_vehicle_requests_applicant', 'vehicle_requests', ['applicant_name'], unique=False, schema='administration')
    op.create_index('ix_vehicle_requests_status', 'vehicle_requests', ['status'], unique=False, schema='administration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_requests_status', table_name='vehicle_requests', schema='administration')
    op.drop_index('ix_vehicle_requests_applicant', table_name='vehicle_requests', schema='administration')
    op.drop_table('vehicle_requests', schema='administration')
    op.drop_index('ix_vehicles_status', table_name='vehicles', schema='administration')
    op.drop_index('ix_vehicles_plate_number', table_name='vehicles', schema='administration')
    op.drop_table('vehicles', schema='administration')
    op.drop_index('ix_it_tickets_type', table_name='it_service_tickets', schema='administration')
    op.drop_index('ix_it_tickets_status', table_name='it_service_tickets', schema='administration')
    op.drop_index('ix_it_tickets_requester', table_name='it_service_tickets', schema='administration')
    op.drop_table('it_service_tickets', schema='administration')
    # ### end Alembic commands ###
