"""regulatory_tracker_restore_fk_constraints

Revision ID: 695b7b28595d
Revises: 9fa375ffef7e
Create Date: 2026-06-30 11:38:00
"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '695b7b28595d'
down_revision: str | None = '9fa375ffef7e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'data_channels', 'data_sources', ['source_id'], ['id'], source_schema='regulatory_tracker', referent_schema='regulatory_tracker', ondelete='CASCADE')
    op.create_foreign_key(None, 'data_channels', 'users', ['updated_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'data_channels', 'users', ['created_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'data_sources', 'users', ['updated_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'data_sources', 'users', ['created_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'regulatory_documents', 'data_sources', ['source_id'], ['id'], source_schema='regulatory_tracker', referent_schema='regulatory_tracker', ondelete='CASCADE')
    op.create_foreign_key(None, 'regulatory_documents', 'data_channels', ['channel_id'], ['id'], source_schema='regulatory_tracker', referent_schema='regulatory_tracker', ondelete='CASCADE')
    op.create_foreign_key(None, 'regulatory_documents', 'users', ['updated_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'regulatory_documents', 'users', ['created_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'sync_job_pages', 'users', ['created_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'sync_job_pages', 'users', ['updated_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'sync_job_pages', 'sync_jobs', ['sync_job_id'], ['id'], source_schema='regulatory_tracker', referent_schema='regulatory_tracker', ondelete='CASCADE')
    op.create_foreign_key(None, 'sync_jobs', 'users', ['created_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'sync_jobs', 'data_sources', ['source_id'], ['id'], source_schema='regulatory_tracker', referent_schema='regulatory_tracker', ondelete='CASCADE')
    op.create_foreign_key(None, 'sync_jobs', 'users', ['updated_by'], ['id'], source_schema='regulatory_tracker', referent_schema='identity')
    op.create_foreign_key(None, 'sync_jobs', 'data_channels', ['channel_id'], ['id'], source_schema='regulatory_tracker', referent_schema='regulatory_tracker', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync_jobs', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'sync_jobs', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'sync_jobs', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'sync_jobs', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'sync_job_pages', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'sync_job_pages', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'sync_job_pages', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'regulatory_documents', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'regulatory_documents', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'regulatory_documents', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'regulatory_documents', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'data_sources', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'data_sources', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'data_channels', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'data_channels', schema='regulatory_tracker', type_='foreignkey')
    op.drop_constraint(None, 'data_channels', schema='regulatory_tracker', type_='foreignkey')
    # ### end Alembic commands ###
