"""add occupational health tables: oh_hazard_monitors, oh_health_exams

Revision ID: 711c184810ba
Revises: 2500b821eece
Create Date: 2026-06-05 15:28:55.815922
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711c184810ba'
down_revision: Union[str, None] = '2500b821eece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oh_hazard_monitors',
    sa.Column('monitor_no', sa.String(length=64), nullable=False, comment='监测编号'),
    sa.Column('workplace', sa.String(length=255), nullable=False, comment='监测场所/车间'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='具体监测点位'),
    sa.Column('equipment_info', sa.String(length=255), nullable=True, comment='关联设备/岗位'),
    sa.Column('detection_type', sa.String(length=32), nullable=False, comment='检测类型: regular/commissioned/evaluation/accident'),
    sa.Column('detection_date', sa.DateTime(timezone=True), nullable=True, comment='检测日期'),
    sa.Column('detection_agency', sa.String(length=255), nullable=True, comment='检测机构'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='状态'),
    sa.Column('inspector_name', sa.String(length=100), nullable=True, comment='检测人员'),
    sa.Column('verifier_name', sa.String(length=100), nullable=True, comment='验证人员'),
    sa.Column('detection_results', sa.JSON(), nullable=True, comment='检测结果 JSON数组 [{factor_name, factor_category, detection_value, unit, oel_limit, compliance_status, sampling_method, standard_ref}]'),
    sa.Column('abnormality_records', sa.JSON(), nullable=True, comment='异常处置记录 JSON数组 [{abnormality_desc, corrective_action, responsible_person, deadline, status, completed_at, remarks}]'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件列表 JSON数组 [{name, path}]'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitor_no', name='uq_oh_hazard_monitors_monitor_no'),
    schema='safety',
    comment='职业危害因素监测表'
    )
    op.create_table('oh_health_exams',
    sa.Column('exam_no', sa.String(length=64), nullable=False, comment='体检编号'),
    sa.Column('employee_name', sa.String(length=100), nullable=False, comment='员工姓名'),
    sa.Column('employee_id', sa.String(length=64), nullable=True, comment='工号'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='部门'),
    sa.Column('job_position', sa.String(length=100), nullable=True, comment='岗位'),
    sa.Column('exam_type', sa.String(length=32), nullable=False, comment='体检类型: pre_employment/periodic/post_employment/emergency'),
    sa.Column('status', sa.String(length=32), server_default='scheduled', nullable=False, comment='状态'),
    sa.Column('exam_agency', sa.String(length=255), nullable=True, comment='体检机构'),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True, comment='计划体检日期'),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=True, comment='实际体检日期'),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True, comment='报告日期'),
    sa.Column('hazard_factors', sa.JSON(), nullable=True, comment='关联的危害因素列表 [string]'),
    sa.Column('overall_conclusion', sa.String(length=32), nullable=True, comment='综合体检结论'),
    sa.Column('exam_items', sa.JSON(), nullable=True, comment='体检项目结果 JSON数组 [{item_name, category, result, reference_range, is_abnormal, remarks}]'),
    sa.Column('abnormality_records', sa.JSON(), nullable=True, comment='异常处置记录 JSON数组'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件列表'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_no', name='uq_oh_health_exams_exam_no'),
    schema='safety',
    comment='职业健康体检表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oh_health_exams', schema='safety')
    op.drop_table('oh_hazard_monitors', schema='safety')
    # ### end Alembic commands ###
