"""enhance_accident_model_investigation_capa

Revision ID: 779629ac4d28
Revises: 711c184810ba
Create Date: 2026-06-05 16:06:36.193571
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779629ac4d28'
down_revision: Union[str, None] = '711c184810ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accidents', sa.Column('department', sa.String(length=100), nullable=True, comment='发生部门'), schema='safety')
    op.add_column('accidents', sa.Column('loss_work_days', sa.Integer(), nullable=True, comment='损失工作日'), schema='safety')
    op.add_column('accidents', sa.Column('injury_details', sa.JSON(), nullable=True, comment='伤员详情 JSON [{"name","position","injury_part","severity","hospital"}]'), schema='safety')
    op.add_column('accidents', sa.Column('investigation_team', sa.JSON(), nullable=True, comment='调查组 JSON [{"name","role"}]'), schema='safety')
    op.add_column('accidents', sa.Column('investigation_method', sa.String(length=100), nullable=True, comment='调查方法: 5-Why/FTA/Event Tree/BowTie等'), schema='safety')
    op.add_column('accidents', sa.Column('investigation_findings', sa.Text(), nullable=True, comment='调查发现'), schema='safety')
    op.add_column('accidents', sa.Column('investigation_report_path', sa.String(length=500), nullable=True, comment='调查报告文件路径'), schema='safety')
    op.add_column('accidents', sa.Column('corrective_action_deadline', sa.DateTime(timezone=True), nullable=True, comment='CAPA截止日期'), schema='safety')
    op.add_column('accidents', sa.Column('corrective_action_responsible', sa.String(length=100), nullable=True, comment='CAPA责任人'), schema='safety')
    op.add_column('accidents', sa.Column('corrective_action_status', sa.String(length=32), nullable=True, comment='CAPA状态: pending/in_progress/completed/verified'), schema='safety')
    op.add_column('accidents', sa.Column('verified_by', sa.UUID(), nullable=True, comment='CAPA验证人'), schema='safety')
    op.add_column('accidents', sa.Column('verified_by_name', sa.String(length=100), nullable=True, comment='验证人姓名'), schema='safety')
    op.add_column('accidents', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='验证时间'), schema='safety')
    op.alter_column('accidents', 'casualties',
               existing_type=sa.VARCHAR(length=255),
               comment='伤亡情况汇总',
               existing_comment='伤亡情况',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态: reported/investigating/investigated/capa_in_progress/closed',
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'reported'::character varying"),
               schema='safety')
    op.create_foreign_key(None, 'accidents', 'users', ['verified_by'], ['id'], source_schema='safety', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accidents', schema='safety', type_='foreignkey')
    op.alter_column('accidents', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态',
               existing_comment='状态: reported/investigating/investigated/capa_in_progress/closed',
               existing_nullable=False,
               existing_server_default=sa.text("'reported'::character varying"),
               schema='safety')
    op.alter_column('accidents', 'casualties',
               existing_type=sa.VARCHAR(length=255),
               comment='伤亡情况',
               existing_comment='伤亡情况汇总',
               existing_nullable=True,
               schema='safety')
    op.drop_column('accidents', 'verified_at', schema='safety')
    op.drop_column('accidents', 'verified_by_name', schema='safety')
    op.drop_column('accidents', 'verified_by', schema='safety')
    op.drop_column('accidents', 'corrective_action_status', schema='safety')
    op.drop_column('accidents', 'corrective_action_responsible', schema='safety')
    op.drop_column('accidents', 'corrective_action_deadline', schema='safety')
    op.drop_column('accidents', 'investigation_report_path', schema='safety')
    op.drop_column('accidents', 'investigation_findings', schema='safety')
    op.drop_column('accidents', 'investigation_method', schema='safety')
    op.drop_column('accidents', 'investigation_team', schema='safety')
    op.drop_column('accidents', 'injury_details', schema='safety')
    op.drop_column('accidents', 'loss_work_days', schema='safety')
    op.drop_column('accidents', 'department', schema='safety')
    # ### end Alembic commands ###
