"""add inspection_task_id to work_orders

Revision ID: 786aeafd60da
Revises: a2eb9476d3c9
Create Date: 2026-06-11 10:39:18.339951
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786aeafd60da'
down_revision: Union[str, None] = 'a2eb9476d3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('inspection_task_id', sa.Uuid(), nullable=True, comment='来源巡检任务ID，由巡检异常自动创建时填入'), schema='equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'inspection_task_id', schema='equipment')
    # ### end Alembic commands ###
