"""add_employee_feishu_open_id

Revision ID: 9061fd906b65
Revises: 2eeaf283689c
Create Date: 2026-06-11 09:46:52.948659
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9061fd906b65'
down_revision: Union[str, None] = '2eeaf283689c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('feishu_open_id', sa.String(length=64), nullable=True, comment='飞书 open_id'), schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'feishu_open_id', schema='hr')
    # ### end Alembic commands ###
