"""add bayesian optimization tables

Revision ID: 983fbcb39a01
Revises: ec4654a030c0
Create Date: 2026-06-10 12:33:22.155516
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '983fbcb39a01'
down_revision: Union[str, None] = 'ec4654a030c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bayesian_projects',
    sa.Column('name', sa.String(length=200), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态: draft/running/completed/failed'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_table('bayesian_components',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='组件名称'),
    sa.Column('lower_bound', sa.Float(), nullable=False, comment='下限'),
    sa.Column('upper_bound', sa.Float(), nullable=False, comment='上限'),
    sa.Column('interval', sa.Float(), nullable=True, comment='间隔'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='单位'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research.bayesian_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_table('bayesian_experiments',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False, comment='批次号'),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='参数组合'),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='实验结果'),
    sa.Column('is_suggested', sa.Boolean(), nullable=False, comment='是否推荐'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态: pending/completed/failed'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research.bayesian_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_table('bayesian_objectives',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='目标名称'),
    sa.Column('direction', sa.String(length=20), nullable=False, comment='优化方向: maximize/minimize'),
    sa.Column('weight', sa.Float(), nullable=False, comment='权重'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research.bayesian_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_table('reaction_scopes',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='范围名称'),
    sa.Column('scope_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='范围数据'),
    sa.Column('total_combinations', sa.Integer(), nullable=False, comment='总组合数'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research.bayesian_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reaction_scopes', schema='research')
    op.drop_table('bayesian_objectives', schema='research')
    op.drop_table('bayesian_experiments', schema='research')
    op.drop_table('bayesian_components', schema='research')
    op.drop_table('bayesian_projects', schema='research')
    # ### end Alembic commands ###
