"""registration_restore_fk_constraints

Revision ID: 9fa375ffef7e
Revises: e3f16bccb5cf
Create Date: 2026-06-30 11:38:00
"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9fa375ffef7e'
down_revision: str | None = 'e3f16bccb5cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'authorization_letters', 'users', ['updated_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'authorization_letters', 'users', ['created_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'drug_nodes', 'users', ['created_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'drug_nodes', 'drugs', ['drug_id'], ['id'], source_schema='registration', referent_schema='registration', ondelete='CASCADE')
    op.create_foreign_key(None, 'drug_nodes', 'users', ['updated_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'drugs', 'users', ['updated_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'drugs', 'users', ['created_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'holidays', 'users', ['created_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'holidays', 'users', ['updated_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'reference_standards', 'users', ['updated_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'reference_standards', 'users', ['created_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'reference_substances', 'users', ['updated_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'reference_substances', 'users', ['created_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'supplementary_replies', 'users', ['updated_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'supplementary_replies', 'users', ['created_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'validation_audit_files', 'users', ['created_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'validation_audit_files', 'users', ['updated_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'validation_audit_issues', 'users', ['updated_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'validation_audit_issues', 'users', ['created_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'validation_audit_knowledge_base', 'users', ['created_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'validation_audit_knowledge_base', 'users', ['updated_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'validation_audit_reports', 'users', ['updated_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'validation_audit_reports', 'users', ['created_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'validation_audit_tasks', 'users', ['updated_by'], ['id'], source_schema='registration', referent_schema='identity')
    op.create_foreign_key(None, 'validation_audit_tasks', 'users', ['created_by'], ['id'], source_schema='registration', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validation_audit_tasks', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'validation_audit_tasks', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'validation_audit_reports', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'validation_audit_reports', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'validation_audit_knowledge_base', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'validation_audit_knowledge_base', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'validation_audit_issues', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'validation_audit_issues', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'validation_audit_files', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'validation_audit_files', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'supplementary_replies', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'supplementary_replies', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'reference_substances', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'reference_substances', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'reference_standards', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'reference_standards', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'holidays', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'holidays', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'drugs', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'drugs', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'drug_nodes', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'drug_nodes', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'drug_nodes', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'authorization_letters', schema='registration', type_='foreignkey')
    op.drop_constraint(None, 'authorization_letters', schema='registration', type_='foreignkey')
    # ### end Alembic commands ###
