"""research_restore_fk_constraints

Revision ID: ac1ba07ef77c
Revises: 695b7b28595d
Create Date: 2026-06-30 11:38:00
"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac1ba07ef77c'
down_revision: str | None = '695b7b28595d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bayesian_components', 'users', ['created_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'bayesian_components', 'users', ['updated_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'bayesian_experiments', 'users', ['created_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'bayesian_experiments', 'users', ['updated_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'bayesian_objectives', 'users', ['created_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'bayesian_objectives', 'users', ['updated_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'bayesian_projects', 'users', ['created_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'bayesian_projects', 'users', ['updated_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'ich_analysis_records', 'users', ['created_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'ich_analysis_records', 'users', ['updated_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'pilot_workflow_steps', 'users', ['created_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'pilot_workflow_steps', 'users', ['updated_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'pilot_workflows', 'users', ['created_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'pilot_workflows', 'users', ['updated_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'process_optimizations', 'users', ['updated_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'process_optimizations', 'users', ['created_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'reaction_scopes', 'users', ['created_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'reaction_scopes', 'users', ['updated_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'research_projects', 'users', ['updated_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'research_projects', 'users', ['created_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'route_developments', 'users', ['created_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'route_developments', 'users', ['updated_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'route_experiments', 'users', ['updated_by'], ['id'], source_schema='research', referent_schema='identity')
    op.create_foreign_key(None, 'route_experiments', 'users', ['created_by'], ['id'], source_schema='research', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route_experiments', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'route_experiments', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'route_developments', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'route_developments', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'research_projects', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'research_projects', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'reaction_scopes', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'reaction_scopes', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'process_optimizations', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'process_optimizations', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'pilot_workflows', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'pilot_workflows', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'pilot_workflow_steps', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'pilot_workflow_steps', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'ich_analysis_records', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'ich_analysis_records', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'bayesian_projects', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'bayesian_projects', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'bayesian_objectives', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'bayesian_objectives', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'bayesian_experiments', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'bayesian_experiments', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'bayesian_components', schema='research', type_='foreignkey')
    op.drop_constraint(None, 'bayesian_components', schema='research', type_='foreignkey')
    # ### end Alembic commands ###
