"""add knowledge articles table

Revision ID: b5875e6adba6
Revises: f1ba2d62f340
Create Date: 2026-06-04 17:20:29.477968
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5875e6adba6'
down_revision: Union[str, None] = 'f1ba2d62f340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_articles',
    sa.Column('title', sa.String(length=255), nullable=False, comment='文章标题'),
    sa.Column('summary', sa.Text(), nullable=True, comment='摘要'),
    sa.Column('content', sa.Text(), nullable=True, comment='正文内容'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签（逗号分隔）'),
    sa.Column('category', sa.String(length=32), server_default='other', nullable=False, comment='分类'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='状态: draft/published/archived'),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False, comment='浏览次数'),
    sa.Column('attachment_path', sa.String(length=500), nullable=True, comment='附件路径'),
    sa.Column('attachment_original_name', sa.String(length=255), nullable=True, comment='附件原始文件名'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='更新人'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_articles', schema='safety')
    # ### end Alembic commands ###
