"""core_restore_fk_constraints

Revision ID: be0d4d96cdda
Revises: 030b01754e94
Create Date: 2026-06-30 11:38:00
"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be0d4d96cdda'
down_revision: str | None = '030b01754e94'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'llm_configs', 'users', ['created_by'], ['id'], source_schema='core', referent_schema='identity')
    op.create_foreign_key(None, 'llm_configs', 'users', ['updated_by'], ['id'], source_schema='core', referent_schema='identity')
    op.drop_index(op.f('ix_module_settings_key'), table_name='module_settings', schema='core')
    op.drop_index(op.f('ix_module_settings_module'), table_name='module_settings', schema='core')
    op.create_index(op.f('ix_core_module_settings_key'), 'module_settings', ['key'], unique=False, schema='core')
    op.create_index(op.f('ix_core_module_settings_module'), 'module_settings', ['module'], unique=False, schema='core')
    op.create_foreign_key(None, 'module_settings', 'users', ['created_by'], ['id'], source_schema='core', referent_schema='identity')
    op.create_foreign_key(None, 'module_settings', 'users', ['updated_by'], ['id'], source_schema='core', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'module_settings', schema='core', type_='foreignkey')
    op.drop_constraint(None, 'module_settings', schema='core', type_='foreignkey')
    op.drop_index(op.f('ix_core_module_settings_module'), table_name='module_settings', schema='core')
    op.drop_index(op.f('ix_core_module_settings_key'), table_name='module_settings', schema='core')
    op.create_index(op.f('ix_module_settings_module'), 'module_settings', ['module'], unique=False, schema='core')
    op.create_index(op.f('ix_module_settings_key'), 'module_settings', ['key'], unique=False, schema='core')
    op.drop_constraint(None, 'llm_configs', schema='core', type_='foreignkey')
    op.drop_constraint(None, 'llm_configs', schema='core', type_='foreignkey')
    # ### end Alembic commands ###
