"""add hr employees table

Revision ID: c7bd8c14dbb8
Revises: 20260529_0001
Create Date: 2026-06-04 14:33:50.910975
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7bd8c14dbb8'
down_revision: Union[str, None] = '20260529_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_number', sa.String(length=32), nullable=False, comment='工号'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='姓名'),
    sa.Column('department', sa.String(length=64), nullable=False, comment='部门'),
    sa.Column('position', sa.String(length=64), nullable=False, comment='职位'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='电话'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('status', sa.String(length=16), server_default='在职', nullable=False, comment='状态: 在职, 离职, 试用期'),
    sa.Column('hire_date', sa.Date(), nullable=False, comment='入职日期'),
    sa.Column('id_card', sa.String(length=18), nullable=True, comment='身份证号'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_number'),
    schema='hr'
    )
    op.create_index('ix_employees_department', 'employees', ['department'], unique=False, schema='hr')
    op.create_index('ix_employees_employee_number', 'employees', ['employee_number'], unique=False, schema='hr')
    op.create_index('ix_employees_status', 'employees', ['status'], unique=False, schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_status', table_name='employees', schema='hr')
    op.drop_index('ix_employees_employee_number', table_name='employees', schema='hr')
    op.drop_index('ix_employees_department', table_name='employees', schema='hr')
    op.drop_table('employees', schema='hr')
    # ### end Alembic commands ###
