"""production_restore_fk_constraints

Revision ID: cf1c5d42c55c
Revises: d182c65334eb
Create Date: 2026-06-30 11:38:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1c5d42c55c'
down_revision: Union[str, None] = 'd182c65334eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'batch_materials', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'batch_materials', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'batch_materials', 'batches', ['batch_id'], ['id'], source_schema='production', referent_schema='production')
    op.create_foreign_key(None, 'batches', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'batches', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'batches', 'process_specs', ['process_spec_id'], ['id'], source_schema='production', referent_schema='production')
    op.create_foreign_key(None, 'data_master', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'data_master', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'label_verifications', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'label_verifications', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'material_balances', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'material_balances', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'material_balances', 'batches', ['batch_id'], ['id'], source_schema='production', referent_schema='production')
    op.create_foreign_key(None, 'notifications', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'notifications', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'ocr_tasks', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'ocr_tasks', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'plan_tasks', 'users', ['assigned_to'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'plan_tasks', 'production_plans', ['plan_id'], ['id'], source_schema='production', referent_schema='production')
    op.create_foreign_key(None, 'plan_tasks', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'plan_tasks', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'point_mappings', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'point_mappings', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'pressure_records', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'pressure_records', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'process_parameters', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'process_parameters', 'process_steps', ['step_id'], ['id'], source_schema='production', referent_schema='production')
    op.create_foreign_key(None, 'process_parameters', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'process_specs', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'process_specs', 'users', ['approved_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'process_specs', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'process_steps', 'process_specs', ['spec_id'], ['id'], source_schema='production', referent_schema='production')
    op.create_foreign_key(None, 'process_steps', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'process_steps', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'production_plans', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'production_plans', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'production_records', 'users', ['created_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'production_records', 'users', ['updated_by'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'production_records', 'users', ['operator'], ['id'], source_schema='production', referent_schema='identity')
    op.create_foreign_key(None, 'production_records', 'batches', ['batch_id'], ['id'], source_schema='production', referent_schema='production')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production_records', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'production_records', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'production_records', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'production_records', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'production_plans', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'production_plans', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'process_steps', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'process_steps', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'process_steps', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'process_specs', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'process_specs', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'process_specs', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'process_parameters', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'process_parameters', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'process_parameters', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'pressure_records', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'pressure_records', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'point_mappings', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'point_mappings', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'plan_tasks', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'plan_tasks', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'plan_tasks', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'plan_tasks', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'ocr_tasks', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'ocr_tasks', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'notifications', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'notifications', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'material_balances', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'material_balances', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'material_balances', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'label_verifications', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'label_verifications', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'data_master', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'data_master', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'batches', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'batches', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'batches', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'batch_materials', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'batch_materials', schema='production', type_='foreignkey')
    op.drop_constraint(None, 'batch_materials', schema='production', type_='foreignkey')
    # ### end Alembic commands ###
