"""add resume_storage_path to candidates

Revision ID: cfdc2edb97f7
Revises: 25374aeacec3
Create Date: 2026-06-09 19:36:20.811865
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdc2edb97f7'
down_revision: Union[str, None] = '25374aeacec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resume_storage_path', sa.String(length=256), nullable=True, comment='本地简历存储路径'), schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'resume_storage_path', schema='hr')
    # ### end Alembic commands ###
