"""identity_restore_fk_constraints

Revision ID: d182c65334eb
Revises: ebe7cc118f4e
Create Date: 2026-06-30 11:38:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd182c65334eb'
down_revision: Union[str, None] = 'ebe7cc118f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'departments', 'users', ['updated_by'], ['id'], source_schema='identity', referent_schema='identity')
    op.create_foreign_key(None, 'departments', 'users', ['created_by'], ['id'], source_schema='identity', referent_schema='identity')
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'], source_schema='identity', referent_schema='identity')
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'], source_schema='identity', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='identity', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='identity', type_='foreignkey')
    op.drop_constraint(None, 'departments', schema='identity', type_='foreignkey')
    op.drop_constraint(None, 'departments', schema='identity', type_='foreignkey')
    # ### end Alembic commands ###
