"""energy_restore_fk_constraints

Revision ID: db60188bf8e4
Revises: 48bece2344cf
Create Date: 2026-06-30 11:38:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db60188bf8e4'
down_revision: Union[str, None] = '48bece2344cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'energy_alert_records', 'users', ['created_by'], ['id'], source_schema='energy', referent_schema='identity')
    op.create_foreign_key(None, 'energy_alert_records', 'energy_alert_rules', ['rule_id'], ['id'], source_schema='energy', referent_schema='energy', ondelete='CASCADE')
    op.create_foreign_key(None, 'energy_alert_records', 'users', ['updated_by'], ['id'], source_schema='energy', referent_schema='identity')
    op.create_foreign_key(None, 'energy_alert_rules', 'users', ['created_by'], ['id'], source_schema='energy', referent_schema='identity')
    op.create_foreign_key(None, 'energy_alert_rules', 'users', ['updated_by'], ['id'], source_schema='energy', referent_schema='identity')
    op.create_foreign_key(None, 'energy_collect_logs', 'users', ['created_by'], ['id'], source_schema='energy', referent_schema='identity')
    op.create_foreign_key(None, 'energy_collect_logs', 'users', ['updated_by'], ['id'], source_schema='energy', referent_schema='identity')
    op.create_foreign_key(None, 'energy_data', 'users', ['updated_by'], ['id'], source_schema='energy', referent_schema='identity')
    op.create_foreign_key(None, 'energy_data', 'users', ['created_by'], ['id'], source_schema='energy', referent_schema='identity')
    op.create_foreign_key(None, 'energy_device_configs', 'users', ['updated_by'], ['id'], source_schema='energy', referent_schema='identity')
    op.create_foreign_key(None, 'energy_device_configs', 'users', ['created_by'], ['id'], source_schema='energy', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'energy_device_configs', schema='energy', type_='foreignkey')
    op.drop_constraint(None, 'energy_device_configs', schema='energy', type_='foreignkey')
    op.drop_constraint(None, 'energy_data', schema='energy', type_='foreignkey')
    op.drop_constraint(None, 'energy_data', schema='energy', type_='foreignkey')
    op.drop_constraint(None, 'energy_collect_logs', schema='energy', type_='foreignkey')
    op.drop_constraint(None, 'energy_collect_logs', schema='energy', type_='foreignkey')
    op.drop_constraint(None, 'energy_alert_rules', schema='energy', type_='foreignkey')
    op.drop_constraint(None, 'energy_alert_rules', schema='energy', type_='foreignkey')
    op.drop_constraint(None, 'energy_alert_records', schema='energy', type_='foreignkey')
    op.drop_constraint(None, 'energy_alert_records', schema='energy', type_='foreignkey')
    op.drop_constraint(None, 'energy_alert_records', schema='energy', type_='foreignkey')
    # ### end Alembic commands ###
