"""quality_restore_fk_constraints

Revision ID: e3f16bccb5cf
Revises: cf1c5d42c55c
Create Date: 2026-06-30 11:38:00
"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e3f16bccb5cf'
down_revision: str | None = 'cf1c5d42c55c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attachment_reviews', 'capas', ['capa_id'], ['id'], source_schema='quality', referent_schema='quality')
    op.create_foreign_key(None, 'attachment_reviews', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'attachment_reviews', 'users', ['reviewer_id'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'attachment_reviews', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'attachment_reviews', 'deviations', ['deviation_id'], ['id'], source_schema='quality', referent_schema='quality')
    op.create_foreign_key(None, 'capas', 'users', ['q_head_approver_id'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'capas', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'capas', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'capas', 'users', ['evaluation_confirmer_id'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'capas', 'users', ['qa_reviewer_id'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'capas', 'deviations', ['deviation_id'], ['id'], source_schema='quality', referent_schema='quality')
    op.create_foreign_key(None, 'cpv_batches', 'cpv_import_tasks', ['import_task_id'], ['id'], source_schema='quality', referent_schema='quality')
    op.create_foreign_key(None, 'cpv_batches', 'cpv_products', ['product_id'], ['id'], source_schema='quality', referent_schema='quality')
    op.create_foreign_key(None, 'cpv_batches', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'cpv_batches', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'cpv_import_tasks', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'cpv_import_tasks', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'cpv_import_tasks', 'cpv_products', ['product_id'], ['id'], source_schema='quality', referent_schema='quality')
    op.create_foreign_key(None, 'cpv_parameters', 'cpv_products', ['product_id'], ['id'], source_schema='quality', referent_schema='quality')
    op.create_foreign_key(None, 'cpv_parameters', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'cpv_parameters', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'cpv_products', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'cpv_products', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'cpv_values', 'cpv_batches', ['batch_id'], ['id'], source_schema='quality', referent_schema='quality')
    op.create_foreign_key(None, 'cpv_values', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'cpv_values', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'cpv_values', 'cpv_parameters', ['parameter_id'], ['id'], source_schema='quality', referent_schema='quality')
    op.create_foreign_key(None, 'department_contacts', 'users', ['production_head_id'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'department_contacts', 'users', ['dept_head_id'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'department_contacts', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'department_contacts', 'users', ['quality_head_id'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'department_contacts', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'department_weekly_confirmations', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'department_weekly_confirmations', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'department_weekly_confirmations', 'users', ['confirmed_by_id'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'deviations', 'users', ['updated_by'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'deviations', 'users', ['reporter_id'], ['id'], source_schema='quality', referent_schema='identity')
    op.create_foreign_key(None, 'deviations', 'users', ['created_by'], ['id'], source_schema='quality', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deviations', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'deviations', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'deviations', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'department_weekly_confirmations', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'department_weekly_confirmations', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'department_weekly_confirmations', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'department_contacts', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'department_contacts', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'department_contacts', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'department_contacts', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'department_contacts', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_values', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_values', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_values', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_values', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_products', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_products', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_parameters', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_parameters', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_parameters', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_import_tasks', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_import_tasks', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_import_tasks', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_batches', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_batches', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_batches', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'cpv_batches', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'capas', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'capas', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'capas', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'capas', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'capas', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'capas', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'attachment_reviews', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'attachment_reviews', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'attachment_reviews', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'attachment_reviews', schema='quality', type_='foreignkey')
    op.drop_constraint(None, 'attachment_reviews', schema='quality', type_='foreignkey')
    # ### end Alembic commands ###
