"""hr_restore_fk_constraints

Revision ID: ebe7cc118f4e
Revises: d39f368e6935
Create Date: 2026-06-30 11:38:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe7cc118f4e'
down_revision: Union[str, None] = 'd39f368e6935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'annual_training_plan_items', 'users', ['created_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'annual_training_plan_items', 'users', ['updated_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'annual_training_plan_items', 'annual_training_plans', ['plan_id'], ['id'], source_schema='hr', referent_schema='hr')
    op.create_foreign_key(None, 'annual_training_plans', 'users', ['created_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'annual_training_plans', 'users', ['updated_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'departments', 'users', ['created_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'departments', 'users', ['updated_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'departure_records', 'users', ['updated_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'departure_records', 'users', ['created_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'employees', 'users', ['updated_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'employees', 'users', ['created_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'offboarding_records', 'users', ['updated_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'offboarding_records', 'employees', ['employee_id'], ['id'], source_schema='hr', referent_schema='hr')
    op.create_foreign_key(None, 'offboarding_records', 'users', ['created_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'onboarding_records', 'users', ['updated_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'onboarding_records', 'users', ['created_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'teams', 'users', ['created_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'teams', 'users', ['updated_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'teams', 'departments', ['department_id'], ['id'], source_schema='hr', referent_schema='hr')
    op.create_foreign_key(None, 'training_ledger_pages', 'users', ['updated_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'training_ledger_pages', 'users', ['created_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'training_ledgers', 'users', ['created_by'], ['id'], source_schema='hr', referent_schema='identity')
    op.create_foreign_key(None, 'training_ledgers', 'users', ['updated_by'], ['id'], source_schema='hr', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_ledgers', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'training_ledgers', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'training_ledger_pages', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'training_ledger_pages', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'teams', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'teams', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'teams', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'onboarding_records', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'onboarding_records', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'offboarding_records', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'offboarding_records', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'offboarding_records', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'employees', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'employees', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'departure_records', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'departure_records', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'departments', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'departments', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'annual_training_plans', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'annual_training_plans', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'annual_training_plan_items', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'annual_training_plan_items', schema='hr', type_='foreignkey')
    op.drop_constraint(None, 'annual_training_plan_items', schema='hr', type_='foreignkey')
    # ### end Alembic commands ###
