"""add hr.teams table

Revision ID: ec4654a030c0
Revises: ca4390627787
Create Date: 2026-06-05 16:02:19.732869
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4654a030c0'
down_revision: Union[str, None] = 'ca4390627787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('name', sa.String(length=64), nullable=False, comment='班组名称'),
    sa.Column('code', sa.String(length=32), nullable=True, comment='班组编码'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='班组描述'),
    sa.Column('department_id', sa.Uuid(), nullable=False, comment='所属部门ID'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['hr.departments.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_teams_department_id', 'teams', ['department_id'], unique=False, schema='hr')
    op.create_index('ix_teams_name', 'teams', ['name'], unique=False, schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teams_name', table_name='teams', schema='hr')
    op.drop_index('ix_teams_department_id', table_name='teams', schema='hr')
    op.drop_table('teams', schema='hr')
    # ### end Alembic commands ###
