"""add_contractor_and_work_record_tables

Revision ID: ecfbd6513afd
Revises: 779629ac4d28
Create Date: 2026-06-05 16:18:37.352850
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecfbd6513afd'
down_revision: Union[str, None] = '779629ac4d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('contractor_no', sa.String(length=64), nullable=False, comment='承包商编号'),
    sa.Column('company_name', sa.String(length=255), nullable=False, comment='公司名称'),
    sa.Column('legal_representative', sa.String(length=100), nullable=True, comment='法定代表人'),
    sa.Column('contact_person', sa.String(length=100), nullable=False, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('business_scope', sa.Text(), nullable=True, comment='经营范围'),
    sa.Column('qualification_type', sa.String(length=32), server_default='other', nullable=False, comment='资质类型'),
    sa.Column('qualification_level', sa.String(length=16), nullable=True, comment='资质等级: grade_a/grade_b/grade_c'),
    sa.Column('qualification_cert_no', sa.String(length=100), nullable=True, comment='资质证书编号'),
    sa.Column('qualification_expiry', sa.DateTime(timezone=True), nullable=True, comment='资质有效期至'),
    sa.Column('safety_license_no', sa.String(length=100), nullable=True, comment='安全生产许可证编号'),
    sa.Column('safety_license_expiry', sa.DateTime(timezone=True), nullable=True, comment='安全生产许可证有效期'),
    sa.Column('insurance_info', sa.Text(), nullable=True, comment='保险信息'),
    sa.Column('insurance_expiry', sa.DateTime(timezone=True), nullable=True, comment='保险有效期至'),
    sa.Column('safety_officer_name', sa.String(length=100), nullable=True, comment='安全负责人'),
    sa.Column('safety_officer_phone', sa.String(length=20), nullable=True, comment='安全负责人电话'),
    sa.Column('special_op_personnel', sa.JSON(), nullable=True, comment='特种作业人员列表 [{"name","cert_type","cert_no","expiry"}]'),
    sa.Column('training_status', sa.String(length=32), server_default='untrained', nullable=False, comment='培训状态: untrained/in_progress/passed/expired'),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=True, comment='最近培训日期'),
    sa.Column('safety_performance_score', sa.Integer(), nullable=True, comment='安全绩效评分（0-100）'),
    sa.Column('blacklisted', sa.Boolean(), server_default='false', nullable=False, comment='是否黑名单'),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False, comment='状态: active/inactive/blacklisted'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contractor_no', name='uq_contractors_contractor_no'),
    schema='safety'
    )
    op.create_table('contractor_work_records',
    sa.Column('contractor_id', sa.UUID(), nullable=False, comment='关联承包商ID'),
    sa.Column('work_content', sa.Text(), nullable=False, comment='施工内容'),
    sa.Column('work_location', sa.String(length=255), nullable=True, comment='施工地点'),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False, comment='计划开始时间'),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False, comment='计划结束时间'),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True, comment='实际开始时间'),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True, comment='实际结束时间'),
    sa.Column('permit_id', sa.UUID(), nullable=True, comment='关联特殊作业票ID'),
    sa.Column('leading_person', sa.String(length=100), nullable=True, comment='带班负责人'),
    sa.Column('worker_count', sa.Integer(), nullable=True, comment='施工人数'),
    sa.Column('safety_briefing_done', sa.Boolean(), server_default='false', nullable=False, comment='安全交底确认'),
    sa.Column('violations', sa.JSON(), nullable=True, comment='违章记录 [{"date","description","severity","handler","result"}]'),
    sa.Column('evaluation', sa.JSON(), nullable=True, comment='评价 {"score","comments","evaluator","date"}'),
    sa.Column('status', sa.String(length=32), server_default='in_progress', nullable=False, comment='状态: in_progress/completed/evaluated'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['safety.contractors.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['permit_id'], ['safety.special_operation_permits.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contractor_work_records', schema='safety')
    op.drop_table('contractors', schema='safety')
    # ### end Alembic commands ###
