"""add special operation personnel and permits

Revision ID: f1ba2d62f340
Revises: 20260604_0001
Create Date: 2026-06-04 16:43:39.297857
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1ba2d62f340'
down_revision: Union[str, None] = '20260604_0001b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_operation_personnel',
    sa.Column('personnel_no', sa.String(length=64), nullable=False, comment='人员编号'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='所属部门'),
    sa.Column('certificate_type', sa.String(length=32), nullable=False, comment='证书类型（对应8种特殊作业）'),
    sa.Column('certificate_number', sa.String(length=100), nullable=True, comment='证书编号'),
    sa.Column('issuing_authority', sa.String(length=200), nullable=True, comment='发证机关'),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True, comment='发证日期'),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True, comment='有效期至'),
    sa.Column('certificate_file_path', sa.String(length=500), nullable=True, comment='证书文件路径'),
    sa.Column('qualification_scope', sa.Text(), nullable=True, comment='资质范围'),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False, comment='状态: active/expired/revoked'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personnel_no', name='uq_special_op_personnel_no'),
    schema='safety'
    )
    op.create_table('special_operation_permits',
    sa.Column('permit_no', sa.String(length=64), nullable=False, comment='作业票编号'),
    sa.Column('operation_type', sa.String(length=32), nullable=False, comment='作业类型（8种）'),
    sa.Column('operation_level', sa.String(length=16), server_default='grade2', nullable=False, comment='作业级别: special/grade1/grade2'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='作业地点'),
    sa.Column('equipment_tag', sa.String(length=100), nullable=True, comment='设备位号'),
    sa.Column('work_description', sa.Text(), nullable=True, comment='作业内容描述'),
    sa.Column('planned_start_time', sa.DateTime(timezone=True), nullable=True, comment='计划开始时间'),
    sa.Column('planned_end_time', sa.DateTime(timezone=True), nullable=True, comment='计划结束时间'),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True, comment='实际开始时间'),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True, comment='实际结束时间'),
    sa.Column('applicant_name', sa.String(length=100), nullable=True, comment='申请人姓名'),
    sa.Column('work_leader_name', sa.String(length=100), nullable=True, comment='作业负责人姓名'),
    sa.Column('operator_names', sa.Text(), nullable=True, comment='作业人员姓名（逗号分隔）'),
    sa.Column('guardian_name', sa.String(length=100), nullable=True, comment='监护人姓名'),
    sa.Column('approver_name', sa.String(length=100), nullable=True, comment='审批人姓名'),
    sa.Column('safety_measures', sa.Text(), nullable=True, comment='安全措施'),
    sa.Column('emergency_equipment', sa.Text(), nullable=True, comment='应急消防器材'),
    sa.Column('gas_analysis', sa.Text(), nullable=True, comment='气体分析结果'),
    sa.Column('risk_assessment', sa.Text(), nullable=True, comment='风险评估'),
    sa.Column('safety_briefing_confirmed', sa.Boolean(), server_default='false', nullable=False, comment='安全交底确认'),
    sa.Column('safety_briefing_time', sa.DateTime(timezone=True), nullable=True, comment='安全交底时间'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='驳回原因'),
    sa.Column('completion_method', sa.String(length=32), nullable=True, comment='完工方式: normal/early_termination'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='状态'),
    sa.Column('check_id', sa.UUID(), nullable=True, comment='关联安全检查ID'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['safety.safety_checks.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permit_no', name='uq_special_op_permits_permit_no'),
    schema='safety'
    )
    op.alter_column('ai_workflow_configs', 'module_code',
               existing_type=sa.VARCHAR(length=64),
               comment='模块代码（hazard-identification / regulation / hazard 等）',
               existing_comment='模块代码',
               existing_nullable=False,
               schema='safety')
    op.alter_column('ai_workflow_configs', 'trigger_event',
               existing_type=sa.VARCHAR(length=64),
               comment='触发事件（submit / revision_created 等）',
               existing_comment='触发事件',
               existing_nullable=True,
               schema='safety')
    op.alter_column('ai_workflow_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='safety')
    op.alter_column('ai_workflow_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='safety')
    op.drop_constraint(op.f('ai_workflow_configs_created_by_fkey'), 'ai_workflow_configs', schema='safety', type_='foreignkey')
    op.drop_constraint(op.f('ai_workflow_configs_updated_by_fkey'), 'ai_workflow_configs', schema='safety', type_='foreignkey')
    op.create_foreign_key(None, 'ai_workflow_configs', 'users', ['created_by'], ['id'], source_schema='safety', referent_schema='identity')
    op.create_foreign_key(None, 'ai_workflow_configs', 'users', ['updated_by'], ['id'], source_schema='safety', referent_schema='identity')
    op.create_table_comment(
        'ai_workflow_configs',
        'AI 工作流配置表',
        existing_comment=None,
        schema='safety'
    )
    op.alter_column('api_call_configs', 'extra_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='额外配置 JSON（system_role 覆盖等）',
               existing_comment='额外配置 JSON',
               existing_nullable=True,
               schema='safety')
    op.alter_column('api_call_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='safety')
    op.alter_column('api_call_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='safety')
    op.drop_constraint(op.f('api_call_configs_updated_by_fkey'), 'api_call_configs', schema='safety', type_='foreignkey')
    op.drop_constraint(op.f('api_call_configs_created_by_fkey'), 'api_call_configs', schema='safety', type_='foreignkey')
    op.create_foreign_key(None, 'api_call_configs', 'users', ['created_by'], ['id'], source_schema='safety', referent_schema='identity')
    op.create_foreign_key(None, 'api_call_configs', 'users', ['updated_by'], ['id'], source_schema='safety', referent_schema='identity')
    op.create_table_comment(
        'api_call_configs',
        'API 调用配置表',
        existing_comment=None,
        schema='safety'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'api_call_configs',
        existing_comment='API 调用配置表',
        schema='safety'
    )
    op.drop_constraint(None, 'api_call_configs', schema='safety', type_='foreignkey')
    op.drop_constraint(None, 'api_call_configs', schema='safety', type_='foreignkey')
    op.create_foreign_key(op.f('api_call_configs_created_by_fkey'), 'api_call_configs', 'users', ['created_by'], ['id'], source_schema='safety', referent_schema='identity', ondelete='SET NULL')
    op.create_foreign_key(op.f('api_call_configs_updated_by_fkey'), 'api_call_configs', 'users', ['updated_by'], ['id'], source_schema='safety', referent_schema='identity', ondelete='SET NULL')
    op.alter_column('api_call_configs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='safety')
    op.alter_column('api_call_configs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='safety')
    op.alter_column('api_call_configs', 'extra_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='额外配置 JSON',
               existing_comment='额外配置 JSON（system_role 覆盖等）',
               existing_nullable=True,
               schema='safety')
    op.drop_table_comment(
        'ai_workflow_configs',
        existing_comment='AI 工作流配置表',
        schema='safety'
    )
    op.drop_constraint(None, 'ai_workflow_configs', schema='safety', type_='foreignkey')
    op.drop_constraint(None, 'ai_workflow_configs', schema='safety', type_='foreignkey')
    op.create_foreign_key(op.f('ai_workflow_configs_updated_by_fkey'), 'ai_workflow_configs', 'users', ['updated_by'], ['id'], source_schema='safety', referent_schema='identity', ondelete='SET NULL')
    op.create_foreign_key(op.f('ai_workflow_configs_created_by_fkey'), 'ai_workflow_configs', 'users', ['created_by'], ['id'], source_schema='safety', referent_schema='identity', ondelete='SET NULL')
    op.alter_column('ai_workflow_configs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='safety')
    op.alter_column('ai_workflow_configs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='safety')
    op.alter_column('ai_workflow_configs', 'trigger_event',
               existing_type=sa.VARCHAR(length=64),
               comment='触发事件',
               existing_comment='触发事件（submit / revision_created 等）',
               existing_nullable=True,
               schema='safety')
    op.alter_column('ai_workflow_configs', 'module_code',
               existing_type=sa.VARCHAR(length=64),
               comment='模块代码',
               existing_comment='模块代码（hazard-identification / regulation / hazard 等）',
               existing_nullable=False,
               schema='safety')
    op.drop_table('special_operation_permits', schema='safety')
    op.drop_table('special_operation_personnel', schema='safety')
    # ### end Alembic commands ###
