"""Equipment repository: re-export all public functions."""

from app.modules.equipment.repository.calibration import (
    create_calibration_plan,
    create_calibration_record,
    delete_calibration_plan,
    get_calibration_plan_by_id,
    get_calibration_plans,
    get_calibration_plans_due,
    get_calibration_record_by_id,
    get_calibration_records,
    update_calibration_plan,
)
from app.modules.equipment.repository.equipment import (
    count_equipments_by_category,
    count_equipments_by_location,
    create_equipment,
    create_equipment_category,
    create_location,
    delete_equipment,
    delete_equipment_category,
    delete_location,
    exists_category_by_code,
    exists_location_by_code,
    get_equipment_by_id,
    get_equipment_by_no,
    get_equipment_categories,
    get_equipment_category_by_id,
    get_equipment_category_tree,
    get_equipment_statistics,
    get_equipments,
    get_location_by_id,
    get_location_tree,
    get_locations,
    get_max_equipment_no_by_category,
    update_equipment,
    update_equipment_category,
    update_location,
)
from app.modules.equipment.repository.failure_code import (
    FailureCodeModel,
    create_failure_code,
    delete_failure_code,
    exists_failure_code_by_code,
    get_failure_code_by_id,
    get_failure_codes,
    update_failure_code,
)
from app.modules.equipment.repository.work_order import (
    count_open_work_orders_by_equipment,
    create_work_order,
    get_max_work_order_no,
    get_work_order_by_id,
    get_work_order_statistics,
    get_work_orders,
)

__all__ = [
    # calibration
    "create_calibration_plan",
    "create_calibration_record",
    "delete_calibration_plan",
    "get_calibration_plan_by_id",
    "get_calibration_plans",
    "get_calibration_plans_due",
    "get_calibration_record_by_id",
    "get_calibration_records",
    "update_calibration_plan",
    # failure code
    "FailureCodeModel",
    "count_equipments_by_category",
    "count_equipments_by_location",
    "count_open_work_orders_by_equipment",
    "create_equipment",
    "create_equipment_category",
    "create_failure_code",
    "create_location",
    "create_work_order",
    "delete_equipment",
    "delete_equipment_category",
    "delete_failure_code",
    "delete_location",
    "exists_category_by_code",
    "exists_failure_code_by_code",
    "exists_location_by_code",
    "get_equipment_by_id",
    "get_equipment_by_no",
    "get_equipment_categories",
    "get_equipment_category_by_id",
    "get_equipment_category_tree",
    "get_equipment_statistics",
    "get_equipments",
    "get_failure_code_by_id",
    "get_failure_codes",
    "get_location_by_id",
    "get_location_tree",
    "get_locations",
    "get_max_equipment_no_by_category",
    "get_max_work_order_no",
    "get_work_order_by_id",
    "get_work_order_statistics",
    "get_work_orders",
    "update_equipment",
    "update_equipment_category",
    "update_failure_code",
    "update_location",
]
