"""add ai_error_message to hazard_identifications

Revision ID: 0a0da5fa3726
Revises: efbe35627071
Create Date: 2026-06-03 17:19:52.942225
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0a0da5fa3726'
down_revision: str | None = 'efbe35627071'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hazard_identifications', sa.Column('ai_error_message', sa.Text(), nullable=True, comment='AI 脚本执行错误信息'), schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hazard_identifications', 'ai_error_message', schema='safety')
    # ### end Alembic commands ###
