"""add report_type to daily_risk_reports

Revision ID: 10b95dc75dcd
Revises: 3fbb2904cf43
Create Date: 2026-06-07 18:09:52.192115
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10b95dc75dcd'
down_revision: Union[str, None] = '3fbb2904cf43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_risk_reports', sa.Column('report_type', sa.String(length=20), server_default='regular', nullable=False, comment='报备类型: regular(常规作业) / non_regular(非常规作业)'), schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_risk_reports', 'report_type', schema='safety')
    # ### end Alembic commands ###
