"""add original_equipment_status to work_orders

Revision ID: 1e3a6f5002da
Revises: 32146cf65fa7
Create Date: 2026-06-03 12:02:40.279062
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3a6f5002da'
down_revision: Union[str, None] = '32146cf65fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('original_equipment_status', sa.String(length=20), nullable=True, comment='创建工单时的设备原始状态'), schema='equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'original_equipment_status', schema='equipment')
    # ### end Alembic commands ###
