"""enhance_training_with_certificates_and_levels

Revision ID: 24b7586df7a5
Revises: ecfbd6513afd
Create Date: 2026-06-05 16:23:41.214038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b7586df7a5'
down_revision: Union[str, None] = 'ecfbd6513afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('safety_trainings', sa.Column('training_level', sa.String(length=32), server_default='dept', nullable=False, comment='培训级别: company/dept/team'), schema='safety')
    op.add_column('safety_trainings', sa.Column('exam_passing_score', sa.Float(), server_default='60', nullable=True, comment='及格分数线'), schema='safety')
    op.add_column('safety_trainings', sa.Column('course_material_path', sa.String(length=500), nullable=True, comment='课程资料路径'), schema='safety')
    op.add_column('training_records', sa.Column('position', sa.String(length=100), nullable=True, comment='岗位'), schema='safety')
    op.add_column('training_records', sa.Column('certificate_no', sa.String(length=100), nullable=True, comment='证书编号'), schema='safety')
    op.add_column('training_records', sa.Column('certificate_expiry', sa.DateTime(timezone=True), nullable=True, comment='证书有效期至'), schema='safety')
    op.add_column('training_records', sa.Column('certificate_status', sa.String(length=32), nullable=True, comment='证书状态: valid/expiring/expired'), schema='safety')
    op.add_column('training_records', sa.Column('certificate_file_path', sa.String(length=500), nullable=True, comment='证书文件路径'), schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_records', 'certificate_file_path', schema='safety')
    op.drop_column('training_records', 'certificate_status', schema='safety')
    op.drop_column('training_records', 'certificate_expiry', schema='safety')
    op.drop_column('training_records', 'certificate_no', schema='safety')
    op.drop_column('training_records', 'position', schema='safety')
    op.drop_column('safety_trainings', 'course_material_path', schema='safety')
    op.drop_column('safety_trainings', 'exam_passing_score', schema='safety')
    op.drop_column('safety_trainings', 'training_level', schema='safety')
    # ### end Alembic commands ###
