"""add ehs_changes table

Revision ID: 2500b821eece
Revises: abc431660f65
Create Date: 2026-06-05 14:50:31.622002
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2500b821eece'
down_revision: Union[str, None] = 'abc431660f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ehs_changes',
    sa.Column('change_no', sa.String(length=64), nullable=False, comment='变更编号'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='变更标题'),
    sa.Column('change_type', sa.String(length=32), nullable=False, comment='变更类型: process_tech/equipment_facility/management'),
    sa.Column('change_grade', sa.String(length=16), server_default='general', nullable=False, comment='变更等级: major/general'),
    sa.Column('change_duration', sa.String(length=16), server_default='permanent', nullable=False, comment='变更期限: permanent/temporary/emergency'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='申请部门'),
    sa.Column('location_unit', sa.String(length=255), nullable=True, comment='所在单元/装置'),
    sa.Column('description', sa.Text(), nullable=True, comment='变更描述（变更前/变更后对比）'),
    sa.Column('technical_basis', sa.Text(), nullable=True, comment='变更技术依据'),
    sa.Column('expected_start', sa.DateTime(timezone=True), nullable=True, comment='预期开始日期'),
    sa.Column('expected_completion', sa.DateTime(timezone=True), nullable=True, comment='预期完成日期'),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True, comment='实际开始日期'),
    sa.Column('actual_completion', sa.DateTime(timezone=True), nullable=True, comment='实际完成日期'),
    sa.Column('expected_effect', sa.Text(), nullable=True, comment='预期效果'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='状态'),
    sa.Column('applicant_id', sa.UUID(), nullable=True, comment='申请人ID'),
    sa.Column('applicant_name', sa.String(length=100), nullable=True, comment='申请人姓名'),
    sa.Column('equipment_tags', sa.JSON(), nullable=True, comment='关联设备位号 JSON数组'),
    sa.Column('documents_to_update', sa.JSON(), nullable=True, comment='需更新的文件清单 JSON数组 [{name, number}]'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件列表 JSON数组 [{name, path}]'),
    sa.Column('risk_assessments', sa.JSON(), nullable=True, comment='风险评估 JSON数组 [{method, severity, likelihood, risk_level, description, control_measures, assessed_by, assessed_date, participants}]'),
    sa.Column('approval_chain', sa.JSON(), nullable=True, comment='审批链 JSON数组 [{level, approver_role, approver, decision, comments, decided_at}]'),
    sa.Column('action_items', sa.JSON(), nullable=True, comment='行动项 JSON数组 [{task, owner, due_date, status, completed_at}]'),
    sa.Column('pssr_checklist', sa.JSON(), nullable=True, comment='PSSR清单 JSON数组 [{item, result, checked_by, checked_at, remarks}]'),
    sa.Column('verification', sa.JSON(), nullable=True, comment='变更验证 {expected_effect_achieved, comments, psi_updated, documents_updated, accepted_by, accepted_date}'),
    sa.Column('closure', sa.JSON(), nullable=True, comment='变更关闭 {closed_by, closed_date, temp_expiry_date, restored_date}'),
    sa.Column('linked_safety_check_id', sa.UUID(), nullable=True, comment='关联安全检查ID（变更验收）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['linked_safety_check_id'], ['safety.safety_checks.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_no', name='uq_ehs_changes_change_no'),
    schema='safety',
    comment='EHS变更管理表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ehs_changes', schema='safety')
    # ### end Alembic commands ###
