"""extend_employees_for_bitable_full_sync

Revision ID: 475080fb7682
Revises: 834188c14ca1
Create Date: 2026-06-05 13:48:14.510658
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475080fb7682'
down_revision: Union[str, None] = '834188c14ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'sort_order', schema='hr')
    op.add_column('employees', sa.Column('domain_account', sa.String(length=64), nullable=True, comment='域账号'), schema='hr')
    op.add_column('employees', sa.Column('team', sa.String(length=64), nullable=True, comment='班组'), schema='hr')
    op.add_column('employees', sa.Column('job_category', sa.String(length=32), nullable=True, comment='职类'), schema='hr')
    op.add_column('employees', sa.Column('level', sa.String(length=32), nullable=True, comment='级别'), schema='hr')
    op.add_column('employees', sa.Column('qualifications', sa.JSON(), nullable=True, comment='职称／职业资格（多选）'), schema='hr')
    op.add_column('employees', sa.Column('qualification_type', sa.String(length=32), nullable=True, comment='职称类型'), schema='hr')
    op.add_column('employees', sa.Column('gender', sa.String(length=8), nullable=True, comment='性别'), schema='hr')
    op.add_column('employees', sa.Column('native_place', sa.String(length=64), nullable=True, comment='籍贯'), schema='hr')
    op.add_column('employees', sa.Column('political_status', sa.String(length=32), nullable=True, comment='政治面貌'), schema='hr')
    op.add_column('employees', sa.Column('marital_status', sa.String(length=16), nullable=True, comment='婚姻状况'), schema='hr')
    op.add_column('employees', sa.Column('household_type', sa.String(length=16), nullable=True, comment='户籍类型'), schema='hr')
    op.add_column('employees', sa.Column('status_category', sa.String(length=32), nullable=True, comment='统计类别'), schema='hr')
    op.add_column('employees', sa.Column('birth_year', sa.Integer(), nullable=True, comment='出生年份'), schema='hr')
    op.add_column('employees', sa.Column('birth_month', sa.Integer(), nullable=True, comment='出生月份'), schema='hr')
    op.add_column('employees', sa.Column('birth_day', sa.Integer(), nullable=True, comment='出生日期'), schema='hr')
    op.add_column('employees', sa.Column('age', sa.Integer(), nullable=True, comment='年龄（飞书公式）'), schema='hr')
    op.add_column('employees', sa.Column('work_start_date', sa.Date(), nullable=True, comment='参加工作时间'), schema='hr')
    op.add_column('employees', sa.Column('factory_entry_date', sa.Date(), nullable=True, comment='进厂时间'), schema='hr')
    op.add_column('employees', sa.Column('livo_entry_date', sa.Date(), nullable=True, comment='入丽珠时间'), schema='hr')
    op.add_column('employees', sa.Column('graduation_date', sa.Date(), nullable=True, comment='毕业时间'), schema='hr')
    op.add_column('employees', sa.Column('work_years', sa.Integer(), nullable=True, comment='工作年限（飞书公式）'), schema='hr')
    op.add_column('employees', sa.Column('factory_tenure', sa.String(length=32), nullable=True, comment='厂龄（飞书公式）'), schema='hr')
    op.add_column('employees', sa.Column('company_tenure', sa.String(length=32), nullable=True, comment='司龄（飞书公式）'), schema='hr')
    op.add_column('employees', sa.Column('classification', sa.String(length=16), nullable=True, comment='分类：全日制/非全日制'), schema='hr')
    op.add_column('employees', sa.Column('school', sa.String(length=128), nullable=True, comment='毕业学校'), schema='hr')
    op.add_column('employees', sa.Column('major', sa.String(length=64), nullable=True, comment='专业'), schema='hr')
    op.add_column('employees', sa.Column('id_card_expiry', sa.String(length=32), nullable=True, comment='身份证到期日'), schema='hr')
    op.add_column('employees', sa.Column('id_card_address', sa.Text(), nullable=True, comment='身份证地址|家庭地址'), schema='hr')
    op.add_column('employees', sa.Column('current_address', sa.Text(), nullable=True, comment='现住址'), schema='hr')
    op.add_column('employees', sa.Column('contract_type', sa.String(length=32), nullable=True, comment='合同期限'), schema='hr')
    op.add_column('employees', sa.Column('contract_start_2', sa.Date(), nullable=True, comment='第二次合同起点'), schema='hr')
    op.add_column('employees', sa.Column('contract_end_2', sa.Date(), nullable=True, comment='第二次合同终止'), schema='hr')
    op.add_column('employees', sa.Column('contract_start_3', sa.Date(), nullable=True, comment='第三次合同起点'), schema='hr')
    op.add_column('employees', sa.Column('contract_end_3', sa.Date(), nullable=True, comment='第三次合同终止'), schema='hr')
    op.add_column('employees', sa.Column('contract_start_4', sa.Date(), nullable=True, comment='第四次合同起点'), schema='hr')
    op.add_column('employees', sa.Column('contract_end_4', sa.Date(), nullable=True, comment='第四次合同终止'), schema='hr')
    op.add_column('employees', sa.Column('emergency_contact_relation', sa.String(length=32), nullable=True, comment='紧急联系人关系'), schema='hr')
    op.add_column('employees', sa.Column('bank_account', sa.String(length=32), nullable=True, comment='银行卡号'), schema='hr')
    op.add_column('employees', sa.Column('training_id', sa.String(length=32), nullable=True, comment='培训档案编号'), schema='hr')
    op.add_column('employees', sa.Column('transfer_history', sa.Text(), nullable=True, comment='异动（含曾经工作部门、岗位)'), schema='hr')
    op.add_column('employees', sa.Column('remarks', sa.JSON(), nullable=True, comment='备注（多选）'), schema='hr')
    op.add_column('employees', sa.Column('feishu_record_id', sa.String(length=32), nullable=True, comment='飞书多维表格 record_id'), schema='hr')
    op.add_column('employees', sa.Column('feishu_synced_at', sa.Date(), nullable=True, comment='上次飞书同步时间'), schema='hr')
    op.alter_column('employees', 'education',
               existing_type=sa.VARCHAR(length=16),
               comment='学历',
               existing_comment='学历: 博士, 硕士, 本科, 大专, 高中, 其他',
               existing_nullable=True,
               schema='hr')
    op.alter_column('employees', 'contract_start_date',
               existing_type=sa.DATE(),
               comment='合同开始日期（第一次）',
               existing_comment='合同开始日期',
               existing_nullable=True,
               schema='hr')
    op.alter_column('employees', 'contract_end_date',
               existing_type=sa.DATE(),
               comment='合同结束日期（第一次）',
               existing_comment='合同结束日期',
               existing_nullable=True,
               schema='hr')
    op.alter_column('employees', 'phone',
               existing_type=sa.VARCHAR(length=32),
               comment='手机',
               existing_comment='电话',
               existing_nullable=True,
               schema='hr')
    op.alter_column('employees', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default='待审批',
               comment='状态: 在职, 离职, 试用期, 待审批',
               existing_comment='状态: 在职, 离职, 试用期',
               existing_nullable=False,
               schema='hr')
    op.create_index('ix_employees_feishu_record_id', 'employees', ['feishu_record_id'], unique=False, schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_feishu_record_id', table_name='employees', schema='hr')
    op.alter_column('employees', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'在职'::character varying"),
               comment='状态: 在职, 离职, 试用期',
               existing_comment='状态: 在职, 离职, 试用期, 待审批',
               existing_nullable=False,
               schema='hr')
    op.alter_column('employees', 'phone',
               existing_type=sa.VARCHAR(length=32),
               comment='电话',
               existing_comment='手机',
               existing_nullable=True,
               schema='hr')
    op.alter_column('employees', 'contract_end_date',
               existing_type=sa.DATE(),
               comment='合同结束日期',
               existing_comment='合同结束日期（第一次）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('employees', 'contract_start_date',
               existing_type=sa.DATE(),
               comment='合同开始日期',
               existing_comment='合同开始日期（第一次）',
               existing_nullable=True,
               schema='hr')
    op.alter_column('employees', 'education',
               existing_type=sa.VARCHAR(length=16),
               comment='学历: 博士, 硕士, 本科, 大专, 高中, 其他',
               existing_comment='学历',
               existing_nullable=True,
               schema='hr')
    op.drop_column('employees', 'feishu_synced_at', schema='hr')
    op.drop_column('employees', 'feishu_record_id', schema='hr')
    op.drop_column('employees', 'remarks', schema='hr')
    op.drop_column('employees', 'transfer_history', schema='hr')
    op.drop_column('employees', 'training_id', schema='hr')
    op.drop_column('employees', 'bank_account', schema='hr')
    op.drop_column('employees', 'emergency_contact_relation', schema='hr')
    op.drop_column('employees', 'contract_end_4', schema='hr')
    op.drop_column('employees', 'contract_start_4', schema='hr')
    op.drop_column('employees', 'contract_end_3', schema='hr')
    op.drop_column('employees', 'contract_start_3', schema='hr')
    op.drop_column('employees', 'contract_end_2', schema='hr')
    op.drop_column('employees', 'contract_start_2', schema='hr')
    op.drop_column('employees', 'contract_type', schema='hr')
    op.drop_column('employees', 'current_address', schema='hr')
    op.drop_column('employees', 'id_card_address', schema='hr')
    op.drop_column('employees', 'id_card_expiry', schema='hr')
    op.drop_column('employees', 'major', schema='hr')
    op.drop_column('employees', 'school', schema='hr')
    op.drop_column('employees', 'classification', schema='hr')
    op.drop_column('employees', 'company_tenure', schema='hr')
    op.drop_column('employees', 'factory_tenure', schema='hr')
    op.drop_column('employees', 'work_years', schema='hr')
    op.drop_column('employees', 'graduation_date', schema='hr')
    op.drop_column('employees', 'livo_entry_date', schema='hr')
    op.drop_column('employees', 'factory_entry_date', schema='hr')
    op.drop_column('employees', 'work_start_date', schema='hr')
    op.drop_column('employees', 'age', schema='hr')
    op.drop_column('employees', 'birth_day', schema='hr')
    op.drop_column('employees', 'birth_month', schema='hr')
    op.drop_column('employees', 'birth_year', schema='hr')
    op.drop_column('employees', 'status_category', schema='hr')
    op.drop_column('employees', 'household_type', schema='hr')
    op.drop_column('employees', 'marital_status', schema='hr')
    op.drop_column('employees', 'political_status', schema='hr')
    op.drop_column('employees', 'native_place', schema='hr')
    op.drop_column('employees', 'gender', schema='hr')
    op.drop_column('employees', 'qualification_type', schema='hr')
    op.drop_column('employees', 'qualifications', schema='hr')
    op.drop_column('employees', 'level', schema='hr')
    op.drop_column('employees', 'job_category', schema='hr')
    op.drop_column('employees', 'team', schema='hr')
    op.drop_column('employees', 'domain_account', schema='hr')
    op.add_column('departments', sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='排序'), schema='hr')
    # ### end Alembic commands ###
