"""add departments table and expand user department fields

Revision ID: 62d4ceac12b4
Revises: a7b8c9d0e1f2
Create Date: 2026-06-07 14:24:48.728860
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '62d4ceac12b4'
down_revision: str | None = 'a7b8c9d0e1f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspection_records', 'task_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='关联巡检任务ID',
               schema='equipment')
    op.alter_column('inspection_tasks', 'equipment_id',
               existing_type=sa.UUID(),
               comment='单设备ID（单设备模式，兼容旧数据）',
               existing_comment='单设备ID（单设备模式）',
               existing_nullable=True,
               schema='equipment')
    op.alter_column('inspection_tasks', 'plan_type',
               existing_type=sa.VARCHAR(length=20),
               comment='巡检类型：日常巡检/周巡检/月巡检/专项巡检',
               existing_comment='巡检类型',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='任务状态：待执行/执行中/已完成/已关闭',
               existing_comment='任务状态',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_tasks', 'overall_result',
               existing_type=sa.VARCHAR(length=10),
               comment='总体结果：正常/异常',
               existing_comment='总体结果',
               existing_nullable=True,
               schema='equipment')
    op.alter_column('work_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态：待处理/执行中/待验收/已完成/已关闭',
               existing_comment='状态：待处理/已指派/维修中/待验收/已完成/已关闭',
               existing_nullable=False,
               schema='equipment')
    op.add_column('users', sa.Column('feishu_department_ids', sa.Text(), nullable=True, comment='飞书部门ID列表，JSON数组'), schema='identity')
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True,
               schema='identity')
    op.alter_column('users', 'position',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True,
               schema='identity')
    op.drop_column('users', 'feishu_department_id', schema='identity')
    op.add_column('accidents', sa.Column('department', sa.String(length=100), nullable=True, comment='发生部门'), schema='safety')
    op.add_column('accidents', sa.Column('loss_work_days', sa.Integer(), nullable=True, comment='损失工作日'), schema='safety')
    op.add_column('accidents', sa.Column('injury_details', sa.JSON(), nullable=True, comment='伤员详情 JSON [{"name","position","injury_part","severity","hospital"}]'), schema='safety')
    op.add_column('accidents', sa.Column('investigation_team', sa.JSON(), nullable=True, comment='调查组 JSON [{"name","role"}]'), schema='safety')
    op.add_column('accidents', sa.Column('investigation_method', sa.String(length=100), nullable=True, comment='调查方法: 5-Why/FTA/Event Tree/BowTie等'), schema='safety')
    op.add_column('accidents', sa.Column('investigation_findings', sa.Text(), nullable=True, comment='调查发现'), schema='safety')
    op.add_column('accidents', sa.Column('investigation_report_path', sa.String(length=500), nullable=True, comment='调查报告文件路径'), schema='safety')
    op.add_column('accidents', sa.Column('corrective_action_deadline', sa.DateTime(timezone=True), nullable=True, comment='CAPA截止日期'), schema='safety')
    op.add_column('accidents', sa.Column('corrective_action_responsible', sa.String(length=100), nullable=True, comment='CAPA责任人'), schema='safety')
    op.add_column('accidents', sa.Column('corrective_action_status', sa.String(length=32), nullable=True, comment='CAPA状态: pending/in_progress/completed/verified'), schema='safety')
    op.add_column('accidents', sa.Column('verified_by', sa.UUID(), nullable=True, comment='CAPA验证人'), schema='safety')
    op.add_column('accidents', sa.Column('verified_by_name', sa.String(length=100), nullable=True, comment='验证人姓名'), schema='safety')
    op.add_column('accidents', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='验证时间'), schema='safety')
    op.alter_column('accidents', 'casualties',
               existing_type=sa.VARCHAR(length=255),
               comment='伤亡情况汇总',
               existing_comment='伤亡情况',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态: reported/investigating/investigated/capa_in_progress/closed',
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'reported'::character varying"),
               schema='safety')
    op.create_foreign_key(None, 'accidents', 'users', ['verified_by'], ['id'], source_schema='safety', referent_schema='identity')
    op.alter_column('hazard_reports', 'hazard_type',
               existing_type=sa.VARCHAR(length=32),
               comment='隐患分类（人/物/环/管）',
               existing_comment='隐患类型',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_level',
               existing_type=sa.VARCHAR(length=16),
               comment='隐患等级（一般/较大/重大）',
               existing_comment='隐患等级',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='计划完成时间',
               existing_comment='整改期限',
               existing_nullable=True,
               schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_records', 'certificate_file_path', schema='safety')
    op.drop_column('training_records', 'certificate_status', schema='safety')
    op.drop_column('training_records', 'certificate_expiry', schema='safety')
    op.drop_column('training_records', 'certificate_no', schema='safety')
    op.drop_column('training_records', 'position', schema='safety')
    op.drop_column('safety_trainings', 'course_material_path', schema='safety')
    op.drop_column('safety_trainings', 'exam_passing_score', schema='safety')
    op.drop_column('safety_trainings', 'training_level', schema='safety')
    op.drop_column('safety_checks', 'safety_officer_confirmed', schema='safety')
    op.drop_column('safety_checks', 'inspector_confirmed', schema='safety')
    op.alter_column('hazard_reports', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='整改期限',
               existing_comment='计划完成时间',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_level',
               existing_type=sa.VARCHAR(length=16),
               comment='隐患等级',
               existing_comment='隐患等级（一般/较大/重大）',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_type',
               existing_type=sa.VARCHAR(length=32),
               comment='隐患类型',
               existing_comment='隐患分类（人/物/环/管）',
               existing_nullable=False,
               schema='safety')
    op.drop_column('hazard_reports', 'rectification_photos', schema='safety')
    op.drop_column('hazard_reports', 'extended_deadline', schema='safety')
    op.drop_column('hazard_reports', 'actual_completion_date', schema='safety')
    op.drop_column('hazard_reports', 'corrective_preventive_measures', schema='safety')
    op.drop_column('hazard_reports', 'rectification_responsible_department', schema='safety')
    op.drop_column('hazard_reports', 'rectification_responsible_person_name', schema='safety')
    op.drop_column('hazard_reports', 'defect_photos', schema='safety')
    op.drop_column('hazard_reports', 'key_defect', schema='safety')
    op.drop_column('hazard_reports', 'major_hazard_basis', schema='safety')
    op.drop_column('hazard_reports', 'hazard_category', schema='safety')
    op.drop_constraint(None, 'accidents', schema='safety', type_='foreignkey')
    op.alter_column('accidents', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态',
               existing_comment='状态: reported/investigating/investigated/capa_in_progress/closed',
               existing_nullable=False,
               existing_server_default=sa.text("'reported'::character varying"),
               schema='safety')
    op.alter_column('accidents', 'casualties',
               existing_type=sa.VARCHAR(length=255),
               comment='伤亡情况',
               existing_comment='伤亡情况汇总',
               existing_nullable=True,
               schema='safety')
    op.drop_column('accidents', 'verified_at', schema='safety')
    op.drop_column('accidents', 'verified_by_name', schema='safety')
    op.drop_column('accidents', 'verified_by', schema='safety')
    op.drop_column('accidents', 'corrective_action_status', schema='safety')
    op.drop_column('accidents', 'corrective_action_responsible', schema='safety')
    op.drop_column('accidents', 'corrective_action_deadline', schema='safety')
    op.drop_column('accidents', 'investigation_report_path', schema='safety')
    op.drop_column('accidents', 'investigation_findings', schema='safety')
    op.drop_column('accidents', 'investigation_method', schema='safety')
    op.drop_column('accidents', 'investigation_team', schema='safety')
    op.drop_column('accidents', 'injury_details', schema='safety')
    op.drop_column('accidents', 'loss_work_days', schema='safety')
    op.drop_column('accidents', 'department', schema='safety')
    op.add_column('users', sa.Column('feishu_department_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='飞书部门ID'), schema='identity')
    op.alter_column('users', 'position',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               schema='identity')
    op.alter_column('users', 'department',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               schema='identity')
    op.drop_column('users', 'feishu_department_ids', schema='identity')
    op.alter_column('work_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态：待处理/已指派/维修中/待验收/已完成/已关闭',
               existing_comment='状态：待处理/执行中/待验收/已完成/已关闭',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_tasks', 'overall_result',
               existing_type=sa.VARCHAR(length=10),
               comment='总体结果',
               existing_comment='总体结果：正常/异常',
               existing_nullable=True,
               schema='equipment')
    op.alter_column('inspection_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='任务状态',
               existing_comment='任务状态：待执行/执行中/已完成/已关闭',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_tasks', 'plan_type',
               existing_type=sa.VARCHAR(length=20),
               comment='巡检类型',
               existing_comment='巡检类型：日常巡检/周巡检/月巡检/专项巡检',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_tasks', 'equipment_id',
               existing_type=sa.UUID(),
               comment='单设备ID（单设备模式）',
               existing_comment='单设备ID（单设备模式，兼容旧数据）',
               existing_nullable=True,
               schema='equipment')
    op.alter_column('inspection_records', 'task_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='关联巡检任务ID',
               schema='equipment')
    op.drop_table('api_call_configs', schema='safety')
    op.drop_table('ai_workflow_configs', schema='safety')
    # ### end Alembic commands ###
