"""enhance_accident_model_investigation_capa

Revision ID: 779629ac4d28
Revises: 711c184810ba
Create Date: 2026-06-05 16:06:36.193571
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779629ac4d28'
down_revision: Union[str, None] = '711c184810ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accidents', 'casualties',
               existing_type=sa.VARCHAR(length=255),
               comment='伤亡情况汇总',
               existing_comment='伤亡情况',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态: reported/investigating/investigated/capa_in_progress/closed',
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'reported'::character varying"),
               schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accidents', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态',
               existing_comment='状态: reported/investigating/investigated/capa_in_progress/closed',
               existing_nullable=False,
               existing_server_default=sa.text("'reported'::character varying"),
               schema='safety')
    op.alter_column('accidents', 'casualties',
               existing_type=sa.VARCHAR(length=255),
               comment='伤亡情况',
               existing_comment='伤亡情况汇总',
               existing_nullable=True,
               schema='safety')
    # ### end Alembic commands ###
