"""add_registration_tables

Revision ID: 7d4e372b86a9
Revises: 1e3a6f5002da
Create Date: 2026-06-05 12:35:55.799183
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d4e372b86a9'
down_revision: str | None = '1e3a6f5002da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugs',
    sa.Column('name', sa.String(length=255), nullable=False, comment='药品名称'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='药品类型：仿制药/创新药/原料药'),
    sa.Column('acceptance_date', sa.Date(), nullable=False, comment='受理日期'),
    sa.Column('current_node', sa.Integer(), nullable=False, comment='当前审评节点'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("type IN ('仿制药', '创新药', '原料药')", name='ck_drugs_type'),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='registration'
    )
    op.create_table('holidays',
    sa.Column('year', sa.Integer(), nullable=False, comment='年份'),
    sa.Column('date', sa.Date(), nullable=False, comment='日期'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型：holiday(节假日)/makeup(补班日)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("type IN ('holiday', 'makeup')", name='ck_holidays_type'),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='registration'
    )
    op.create_table('drug_nodes',
    sa.Column('drug_id', sa.Uuid(), nullable=False, comment='药品ID'),
    sa.Column('node_index', sa.Integer(), nullable=False, comment='节点序号（1-10）'),
    sa.Column('actual_date', sa.Date(), nullable=True, comment='实际完成日期'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['registration.drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id', 'node_index', 'is_deleted', name='uq_drug_nodes_drug_node'),
    schema='registration'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drug_nodes', schema='registration')
    op.drop_table('holidays', schema='registration')
    op.drop_table('drugs', schema='registration')
    # ### end Alembic commands ###
