"""add departments and offboarding tables, extend employees

Revision ID: 834188c14ca1
Revises: c7bd8c14dbb8
Create Date: 2026-06-04 20:29:27.142054
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834188c14ca1'
down_revision: Union[str, None] = 'c7bd8c14dbb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=64), nullable=False, comment='部门名称'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='部门编码'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='部门描述'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='hr'
    )
    op.create_index('ix_departments_code', 'departments', ['code'], unique=False, schema='hr')
    op.create_table('offboarding_records',
    sa.Column('employee_id', sa.Uuid(), nullable=False, comment='员工ID'),
    sa.Column('offboarding_date', sa.Date(), nullable=False, comment='离职日期'),
    sa.Column('offboarding_type', sa.String(length=16), server_default='辞职', nullable=False, comment='离职类型: 辞职, 辞退, 合同到期, 退休, 其他'),
    sa.Column('reason', sa.String(length=512), nullable=True, comment='离职原因'),
    sa.Column('handover_status', sa.String(length=16), server_default='待交接', nullable=False, comment='交接状态: 待交接, 交接中, 已完成'),
    sa.Column('notes', sa.String(length=512), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['hr.employees.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_offboarding_date', 'offboarding_records', ['offboarding_date'], unique=False, schema='hr')
    op.create_index('ix_offboarding_employee_id', 'offboarding_records', ['employee_id'], unique=False, schema='hr')
    op.add_column('employees', sa.Column('education', sa.String(length=16), nullable=True, comment='学历: 博士, 硕士, 本科, 大专, 高中, 其他'), schema='hr')
    op.add_column('employees', sa.Column('emergency_contact_name', sa.String(length=64), nullable=True, comment='紧急联系人姓名'), schema='hr')
    op.add_column('employees', sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True, comment='紧急联系人电话'), schema='hr')
    op.add_column('employees', sa.Column('contract_start_date', sa.Date(), nullable=True, comment='合同开始日期'), schema='hr')
    op.add_column('employees', sa.Column('contract_end_date', sa.Date(), nullable=True, comment='合同结束日期'), schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'contract_end_date', schema='hr')
    op.drop_column('employees', 'contract_start_date', schema='hr')
    op.drop_column('employees', 'emergency_contact_phone', schema='hr')
    op.drop_column('employees', 'emergency_contact_name', schema='hr')
    op.drop_column('employees', 'education', schema='hr')
    op.drop_index('ix_offboarding_employee_id', table_name='offboarding_records', schema='hr')
    op.drop_index('ix_offboarding_date', table_name='offboarding_records', schema='hr')
    op.drop_table('offboarding_records', schema='hr')
    op.drop_index('ix_departments_code', table_name='departments', schema='hr')
    op.drop_table('departments', schema='hr')
    # ### end Alembic commands ###
