"""remove_duplicate_fields

Revision ID: a9387cd590c5
Revises: c86418e170c2
Create Date: 2026-06-04 15:17:10.396245
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9387cd590c5'
down_revision: Union[str, None] = 'c86418e170c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('hazard_reports_rectification_responsible_person_fkey'), 'hazard_reports', schema='safety', type_='foreignkey')
    op.drop_column('hazard_reports', 'planned_completion_date', schema='safety')
    op.drop_column('hazard_reports', 'rectification_responsible_person', schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hazard_reports', sa.Column('rectification_responsible_person', sa.UUID(), autoincrement=False, nullable=True, comment='整改责任人'), schema='safety')
    op.add_column('hazard_reports', sa.Column('planned_completion_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='计划完成时间'), schema='safety')
    op.create_foreign_key(op.f('hazard_reports_rectification_responsible_person_fkey'), 'hazard_reports', 'users', ['rectification_responsible_person'], ['id'], source_schema='safety', referent_schema='identity')
    # ### end Alembic commands ###
