"""add_special_operation_reports_and_daily_risk_reports

Revision ID: abc431660f65
Revises: b5875e6adba6
Create Date: 2026-06-05 14:27:18.549506
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'abc431660f65'
down_revision: str | None = 'b5875e6adba6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_risk_reports',
    sa.Column('report_no', sa.String(length=64), nullable=False, comment='报备编号'),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False, comment='报备作业日期'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='报备部门'),
    sa.Column('hazard_identification_id', sa.UUID(), nullable=True, comment='关联危险源辨识ID'),
    sa.Column('operation_description', sa.Text(), nullable=False, comment='风险作业描述'),
    sa.Column('operation_steps', sa.Text(), nullable=True, comment='作业步骤'),
    sa.Column('hazard_factors', sa.Text(), nullable=True, comment='危险因素'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='风险等级: level_1/level_2/level_3/level_4'),
    sa.Column('control_measures', sa.Text(), nullable=True, comment='控制措施'),
    sa.Column('responsible_person', sa.String(length=100), nullable=True, comment='作业负责人'),
    sa.Column('operator_count', sa.Integer(), nullable=True, comment='作业人数'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='作业地点'),
    sa.Column('planned_start_time', sa.DateTime(timezone=True), nullable=True, comment='计划开始时间'),
    sa.Column('planned_end_time', sa.DateTime(timezone=True), nullable=True, comment='计划结束时间'),
    sa.Column('applicant_name', sa.String(length=100), nullable=True, comment='报备申请人姓名'),
    sa.Column('approver_name', sa.String(length=100), nullable=True, comment='审批人姓名'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='审批时间'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='驳回原因'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='状态: draft/submitted/approved/rejected'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['hazard_identification_id'], ['safety.hazard_identifications.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_no', name='uq_daily_risk_reports_no'),
    schema='safety'
    )
    op.create_table('special_operation_reports',
    sa.Column('report_no', sa.String(length=64), nullable=False, comment='报备编号'),
    sa.Column('permit_id', sa.UUID(), nullable=True, comment='关联作业票ID'),
    sa.Column('operation_type', sa.String(length=32), nullable=False, comment='作业类型（8种）'),
    sa.Column('operation_level', sa.String(length=16), server_default='grade2', nullable=False, comment='作业级别: special/grade1/grade2'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='报备部门'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='作业地点'),
    sa.Column('equipment_tag', sa.String(length=100), nullable=True, comment='设备位号'),
    sa.Column('work_description', sa.Text(), nullable=True, comment='作业内容描述'),
    sa.Column('planned_start_time', sa.DateTime(timezone=True), nullable=True, comment='计划开始时间'),
    sa.Column('planned_end_time', sa.DateTime(timezone=True), nullable=True, comment='计划结束时间'),
    sa.Column('work_leader_name', sa.String(length=100), nullable=True, comment='作业负责人姓名'),
    sa.Column('operator_names', sa.Text(), nullable=True, comment='作业人员姓名（逗号分隔）'),
    sa.Column('guardian_name', sa.String(length=100), nullable=True, comment='监护人姓名'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='风险等级: level_1/level_2/level_3/level_4'),
    sa.Column('safety_measures', sa.Text(), nullable=True, comment='安全措施'),
    sa.Column('emergency_equipment', sa.Text(), nullable=True, comment='应急消防器材'),
    sa.Column('gas_analysis', sa.Text(), nullable=True, comment='气体分析结果'),
    sa.Column('risk_assessment', sa.Text(), nullable=True, comment='风险评估描述'),
    sa.Column('applicant_name', sa.String(length=100), nullable=True, comment='报备申请人姓名'),
    sa.Column('approver_name', sa.String(length=100), nullable=True, comment='审批人姓名'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='审批时间'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='驳回原因'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='状态: draft/submitted/approved/rejected'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['permit_id'], ['safety.special_operation_permits.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_no', name='uq_special_operation_reports_no'),
    schema='safety'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('special_operation_reports', schema='safety')
    op.drop_table('daily_risk_reports', schema='safety')
    # ### end Alembic commands ###
