"""add operation regulations revision and hazard revision tables

Revision ID: c86418e170c2
Revises: 63e0261d5871
Create Date: 2026-06-04 14:42:12.069263
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86418e170c2'
down_revision: Union[str, None] = '63e0261d5871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
