"""add importance to equipment

Revision ID: f068904911a9
Revises: 99e9cdbbe4ac
Create Date: 2026-06-05 15:47:45.431010
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f068904911a9'
down_revision: str | None = '99e9cdbbe4ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column('equipments', sa.Column('importance', sa.String(length=10), nullable=True, comment='设备重要性：高/中/低'), schema='equipment')
    op.execute("UPDATE equipment.equipments SET importance = '低' WHERE importance IS NULL")
    op.alter_column('equipments', 'importance', schema='equipment', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipments', 'importance', schema='equipment')
    # ### end Alembic commands ###
