"""change needs_recommendation from boolean to string

Revision ID: fb2c920c3d32
Revises: 0a0da5fa3726
Create Date: 2026-06-04 14:24:49.212772
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fb2c920c3d32'
down_revision: str | None = '0a0da5fa3726'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hazard_identifications', 'needs_recommendation',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               comment='是否需提出建议措施（是/否/待人工确认）',
               existing_comment='是否需提出建议措施',
               existing_nullable=True,
               schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hazard_identifications', 'needs_recommendation',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               comment='是否需提出建议措施',
               existing_comment='是否需提出建议措施（是/否/待人工确认）',
               existing_nullable=True,
               schema='safety')
    # ### end Alembic commands ###
